# backend/prod.hcl -- generated by pipeline-automator scaffold (project init)
# Backend configuration for the prod state of payroll_pipeline.
# Passed to `terraform init -backend-config=backend/prod.hcl` by the
# deploy workflow. The environment segment in `key` is what keeps environments
# in separate state files -- do not remove it.

bucket         = "payroll_pipeline_tfstate"
key            = "payroll_pipeline/prod/terraform.tfstate"
region         = "eu-west-1"
dynamodb_table = "terraform-locks"
encrypt        = true
