# modules/glue/main.tf -- generated by pipeline-automator scaffold (project init)
# Glue ETL jobs for this data product. One aws_glue_job resource is created per
# entry in var.jobs via for_each. Job scripts are read from the scripts bucket at
# s3://{scripts_bucket_name}/scripts/{job_name}/{job_name}.py

locals {
  common_tags = merge(var.tags, {
    Environment = var.environment
    ManagedBy   = "terraform"
  })
}

data "aws_caller_identity" "current" {}

resource "aws_glue_job" "etl" {
  for_each = var.jobs

  name         = "${var.name_prefix}-${each.key}"
  role_arn     = var.role_arn
  glue_version = "5.0"
  max_retries  = 0

  worker_type       = each.value.worker_type
  number_of_workers = each.value.number_of_workers

  execution_property {
    max_concurrent_runs = 2
  }

  command {
    name            = "glueetl"
    python_version  = "3"
    script_location = "s3://${var.scripts_bucket_name}/scripts/${each.key}/${each.key}.py"
  }

  default_arguments = {
    "--job-language"                     = "python"
    "--enable-metrics"                   = "true"
    "--enable-continuous-cloudwatch-log" = "true"
    "--extra-py-files"                   = "s3://${var.scripts_bucket_name}/${var.package_object_key}"
    # --extra-py-files only uploads this project's own wheel, not its third-party
    # dependencies -- pipeline/validate.py imports PyYAML at module scope, and Glue's
    # own bootstrap pip-installs whatever --additional-python-modules names, so this is
    # what actually gets it onto the worker (declaring it in pyproject.toml's
    # dependencies alone only governs a dev/CI `pip install`, not the Glue runtime).
    "--additional-python-modules" = "pyyaml==6.0.2"
    "--TempDir"                   = "s3://${var.scripts_bucket_name}/temp/"
    "--environment"               = var.environment
    # --datalake-formats puts Iceberg on the classpath. --catalog_database_prefix
    # composes the deploy-environment-specific database name at runtime (job_settings.py's
    # JobContext.table_identity) -- it is never baked into the job script itself, because
    # the script is rendered once and deployed to every environment.
    "--datalake-formats"        = "iceberg"
    "--catalog_database_prefix" = replace(var.name_prefix, "-", "_")
    # Key set verified against AWS's Iceberg REST catalog documentation
    # (docs.aws.amazon.com/glue/latest/dg/connect-glu-iceberg-rest.html); deliberately no
    # rest.signing-region key, which does not appear in AWS's own example.
    "--conf" = join(" ", [
      "spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions",
      "--conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog",
      "--conf spark.sql.catalog.glue_catalog.type=rest",
      "--conf spark.sql.catalog.glue_catalog.uri=https://glue.${var.aws_region}.amazonaws.com/iceberg",
      "--conf spark.sql.catalog.glue_catalog.warehouse=${data.aws_caller_identity.current.account_id}",
      "--conf spark.sql.catalog.glue_catalog.rest.sigv4-enabled=true",
      "--conf spark.sql.catalog.glue_catalog.rest.signing-name=glue",
      "--conf spark.sql.defaultCatalog=glue_catalog",
    ])
  }

  tags = local.common_tags
}
