# modules/glue/outputs.tf -- generated by pipeline-automator scaffold (project init)

output "job_names" {
  description = "Map of job key to the full Glue job name."
  value       = { for k, v in aws_glue_job.etl : k => v.name }
}

output "job_arns" {
  description = "Map of job key to the Glue job ARN."
  value       = { for k, v in aws_glue_job.etl : k => v.arn }
}
