# modules/glue/variables.tf -- generated by pipeline-automator scaffold (project init)

variable "name_prefix" {
  description = "Prefix applied to Glue job names (typically '<data_product>-<environment>')."
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "aws_region" {
  description = "AWS region the Iceberg REST catalog endpoint is reached in."
  type        = string
}

variable "jobs" {
  description = "Map of ETL job names to their worker configuration. Populated by the scaffolder when ETL jobs are added."
  type = map(object({
    number_of_workers = number
    worker_type       = string
  }))
}

variable "role_arn" {
  description = "ARN of the IAM role the Glue jobs assume."
  type        = string
}

variable "scripts_bucket_name" {
  description = "Name of the S3 bucket holding job scripts and the shared temp directory."
  type        = string
}

variable "package_object_key" {
  description = "S3 key of the Python library archive passed to Glue via --extra-py-files."
  type        = string
  default     = "lib/payroll_pipeline.whl"
}

variable "tags" {
  description = "Tags applied to all Glue job resources."
  type        = map(string)
  default     = {}
}
