# test_prepare_payroll_register_pipeline.py -- generated by pipeline-automator generate (create-job)
# Structural end-to-end test only: the whole pipeline (read -> transform -> validate ->
# write) runs locally, through the job's own real entrypoint, and produces a well-formed
# sink table. This asserts structure -- schema, uniqueness, non-null constraints, a
# passing validation block, a well-formed run record -- never business values.
# Expected-value assertions require knowing what the numbers should be, which is
# R2.6/R2.7's `generate tests`, not this tier.

from __future__ import annotations

import json
import sys
from decimal import Decimal
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

from payroll_pipeline.tests._schema_fixtures import (
    assert_schema_matches,
    synthetic_frame_for,
    transformation_cases,
)

if TYPE_CHECKING:
    from pyspark.sql import SparkSession

_CATALOG_DATABASE_PREFIX = "test"
_START_DATE = "2024-01-01"
_END_DATE = "2024-01-03"


def _terminal_case_expected() -> list[dict[str, str]]:
    """The terminal transformation's predicted output schema, from `transformation_cases`."""
    for case in transformation_cases("prepare_payroll_register"):
        if case.name == "combine_regular_and_retro_pay":
            return case.expected
    raise AssertionError(
        "no case named 'combine_regular_and_retro_pay' in transformation_cases('prepare_payroll_register')",
    )


_TERMINAL_SCHEMA = _terminal_case_expected()

_UNIQUE_KEY = [
    "payroll_register_key",
]

_PAYROLL_REGISTER_RAW_SCHEMA: list[dict[str, str]] = [
    {"name": "employee_id", "type": "string"},
    {"name": "pay_run_id", "type": "string"},
    {"name": "pay_period", "type": "string"},
    {"name": "pay_date", "type": "string"},
    {"name": "run_type", "type": "string"},
    {"name": "lohnart_code", "type": "string"},
    {"name": "component_name", "type": "string"},
    {"name": "gl_account", "type": "string"},
    {"name": "cost_center_code", "type": "string"},
    {"name": "location_code", "type": "string"},
    {"name": "bearer", "type": "string"},
    {"name": "amount_eur", "type": "decimal(14,2)"},
    {"name": "assessment_base_eur", "type": "decimal(14,2)"},
    {"name": "quantity", "type": "decimal(12,4)"},
    {"name": "rate", "type": "decimal(12,6)"},
]
_PAYROLL_REGISTER_RAW_ROWS: list[tuple[Any, ...]] = [
    ("employee_id_0", "pay_run_id_0", "pay_period_0", "pay_date_0", "run_type_0", "lohnart_code_0", "component_name_0", "gl_account_0", "cost_center_code_0", "location_code_0", "bearer_0", Decimal("1"), Decimal("1"), Decimal("1"), Decimal("1")),
    ("employee_id_1", "pay_run_id_1", "pay_period_1", "pay_date_1", "run_type_1", "lohnart_code_1", "component_name_1", "gl_account_1", "cost_center_code_1", "location_code_1", "bearer_1", Decimal("2"), Decimal("2"), Decimal("2"), Decimal("2")),
]


@pytest.mark.end_to_end
def test_pipeline_runs_and_produces_a_well_formed_table(
    spark: SparkSession, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """Run prepare_payroll_register through its real entrypoint and check the result is well-formed.

    Applies the generated catalog DDL to this test's own database (substituting
    `{catalog_database_prefix}_{layer}` for `${CATALOG_DATABASE}`, the same composition
    `JobContext.table_identity` uses at runtime, so the job writes to exactly the table
    this test then reads), seeds each owned source, then drives the job through its own
    `run()` -- never a hand-built `JobContext` -- so argument resolution, window
    defaulting, and run-record emission are exercised too, not bypassed.
    """
    ddl_path = (
        Path(__file__)
        .resolve()
        .parents[4]
        .joinpath(
            "infra",
            "catalog",
            "preprocessed__payroll_register.sql",
        )
    )
    sink_database = f"{_CATALOG_DATABASE_PREFIX}_preprocessed"
    ddl = ddl_path.read_text(encoding="utf-8").replace("${CATALOG_DATABASE}", sink_database)
    spark.sql(ddl.strip().rstrip(";"))

    payroll_register_raw_table = f"{_CATALOG_DATABASE_PREFIX}_raw.payroll_register"
    payroll_register_raw_seed_frame = synthetic_frame_for(
        spark,
        _PAYROLL_REGISTER_RAW_SCHEMA,
        _PAYROLL_REGISTER_RAW_ROWS,
    )
    payroll_register_raw_seed_frame.writeTo(payroll_register_raw_table).using("iceberg").create()

    # argv[0] is the program name -- argparse and getResolvedOptions alike skip it and
    # parse argv[1:], so omitting it would consume the first real flag as the program name.
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "prepare_payroll_register.py",
            "--start_date",
            _START_DATE,
            "--end_date",
            _END_DATE,
            "--environment",
            "test",
            "--catalog_database_prefix",
            _CATALOG_DATABASE_PREFIX,
        ],
    )

    from payroll_pipeline.jobs.prepare_payroll_register import prepare_payroll_register as job

    job.run()

    captured = capsys.readouterr()
    record_lines = [line for line in captured.out.splitlines() if line.startswith("RUN_RECORD ")]
    assert len(record_lines) == 1, f"expected exactly one RUN_RECORD line, got {record_lines}"
    record = json.loads(record_lines[0].removeprefix("RUN_RECORD "))
    assert record["status"] == "SUCCEEDED", record
    assert record["phase"] is None, record
    assert record["metrics"]["validation"]["ok"] is True, record["metrics"]["validation"]

    sink_table = f"{sink_database}.payroll_register"
    sink_df = spark.table(sink_table)

    assert sink_df.count() > 0, f"sink table {sink_table} is empty"
    assert_schema_matches(sink_df.schema, _TERMINAL_SCHEMA)

    assert sink_df.count() == sink_df.dropDuplicates(_UNIQUE_KEY).count(), (
        f"grain.unique_key {_UNIQUE_KEY} is not unique in {sink_table}"
    )

    not_null_columns = [f.name for f in sink_df.schema.fields if not f.nullable]
    for column in not_null_columns:
        null_count = sink_df.filter(sink_df[column].isNull()).count()
        assert null_count == 0, f"NOT NULL column {column!r} holds a null in {sink_table}"
