# modules/s3/main.tf -- generated by pipeline-automator scaffold (project init)
# Medallion data lakehouse buckets for the data product.
# Four buckets are created via for_each: raw, preprocessed, processed, scripts.

locals {
  common_tags = merge(var.tags, {
    Environment = var.environment
    ManagedBy   = "terraform"
    Module      = "s3"
  })
}

resource "aws_s3_bucket" "medallion" {
  for_each = var.bucket_names

  bucket = "${var.name_prefix}-${each.value}"
  tags   = merge(local.common_tags, { Role = each.key })
}

resource "aws_s3_bucket_versioning" "medallion" {
  for_each = var.bucket_names

  bucket = aws_s3_bucket.medallion[each.key].id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "medallion" {
  for_each = var.bucket_names

  bucket = aws_s3_bucket.medallion[each.key].id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "aws:kms"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "medallion" {
  for_each = var.bucket_names

  bucket                  = aws_s3_bucket.medallion[each.key].id
  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}


resource "aws_s3_bucket_lifecycle_configuration" "medallion" {
  for_each = var.lifecycle_rules_enabled ? var.bucket_names : {}

  bucket = aws_s3_bucket.medallion[each.key].id

  rule {
    id     = "cost-management"
    status = "Enabled"

    transition {
      days          = 0
      storage_class = "INTELLIGENT_TIERING"
    }

    noncurrent_version_expiration {
      noncurrent_days = var.noncurrent_version_expiration_days
    }
  }
}
