# modules/s3/outputs.tf -- generated by pipeline-automator scaffold (project init)

output "bucket_arns" {
  description = "Map of bucket role to ARN for all medallion buckets."
  value       = { for k, v in aws_s3_bucket.medallion : k => v.arn }
}

output "bucket_names" {
  description = "Map of bucket role to bucket name for all medallion buckets."
  value       = { for k, v in aws_s3_bucket.medallion : k => v.bucket }
}
