# modules/s3/variables.tf -- generated by pipeline-automator scaffold (project init)

variable "name_prefix" {
  description = "Prefix applied to all bucket names (typically '<data_product>-<environment>')."
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "bucket_names" {
  description = "Map of logical bucket roles to their name suffixes. Combined with name_prefix to form the full bucket name."
  type        = map(string)
  default = {
    raw          = "raw"
    preprocessed = "preprocessed"
    processed    = "processed"
    scripts      = "scripts"
  }
}

variable "lifecycle_rules_enabled" {
  description = "Whether to enable intelligent-tiering and noncurrent version expiration lifecycle rules."
  type        = bool
  default     = true
}

variable "noncurrent_version_expiration_days" {
  description = "Days after which noncurrent object versions are expired."
  type        = number
  default     = 90
}

variable "tags" {
  description = "Tags applied to all resources in this module."
  type        = map(string)
  default     = {}
}
