# prepare_payroll_register.py -- generated by pipeline-automator generate (create-job / codegen)
# Structure (imports, JOB_CONFIG, transform() signature, run()) is scaffold-owned;
# transformation bodies live in prepare_payroll_register_transformations.py. This exact file is
# uploaded unchanged to Glue's script_location -- it is the job's entrypoint.

from pyspark.sql import DataFrame

from payroll_pipeline.jobs.prepare_payroll_register.prepare_payroll_register_transformations import (
    cast_data_types,
    combine_regular_and_retro_pay,
    create_unique_key,
    filter_regular_runs,
    filter_retro_runs,
    join_regular_and_retro_data,
    sum_retro_amounts,
)
from payroll_pipeline.runtime.job_settings import (
    JobConfig,
    SinkConfig,
    SourceConfig,
    job_run,
)
from payroll_pipeline.runtime.run import run as _run

JOB_CONFIG = JobConfig(
    job_name="prepare_payroll_register",
    contract_package="payroll_pipeline.contracts",
    sources=(
        SourceConfig(
            alias="payroll_register_raw",
            layer="raw",
            dataset="payroll_register",
            table_identity=None,
            partition_column="pay_date",
            partition_column_type="string",
            columns=(
                "employee_id:string",
                "pay_run_id:string",
                "pay_period:string",
                "pay_date:string",
                "run_type:string",
                "lohnart_code:string",
                "component_name:string",
                "gl_account:string",
                "cost_center_code:string",
                "location_code:string",
                "bearer:string",
                "amount_eur:decimal(14,2)",
                "assessment_base_eur:decimal(14,2)",
                "quantity:decimal(12,4)",
                "rate:decimal(12,6)",
            ),
            contact="data-eng@example.com",
            allow_empty=False,
        ),
    ),
    sink=SinkConfig(
        layer="preprocessed",
        dataset="payroll_register",
        write_mode="overwrite_partitions",
    ),
)


def transform(sources: dict[str, DataFrame]) -> DataFrame:
    payroll_register_raw = sources["payroll_register_raw"]
    create_unique_key_result = create_unique_key(payroll_register_raw)
    cast_data_types_result = cast_data_types(create_unique_key_result)
    filter_retro_runs_result = filter_retro_runs(cast_data_types_result)
    filter_regular_runs_result = filter_regular_runs(cast_data_types_result)
    sum_retro_amounts_result = sum_retro_amounts(filter_retro_runs_result)
    join_regular_and_retro_data_result = join_regular_and_retro_data(filter_regular_runs_result, sum_retro_amounts_result)
    output = combine_regular_and_retro_pay(join_regular_and_retro_data_result)
    return output


def run() -> None:
    """Resolve runtime settings, then execute read -> transform -> validate -> write once."""
    with job_run(JOB_CONFIG) as (ctx, record):
        _run(ctx, record, JOB_CONFIG, transform_fn=transform)


if __name__ == "__main__":
    run()
