-- preprocessed__payroll_register.sql -- generated by pipeline-automator generate
-- (create-job). Rendered from the job's resolved sink schema. Do not edit by
-- hand; edit the job spec or the source contracts and re-run
-- `generate create-job --update`.

CREATE TABLE IF NOT EXISTS ${CATALOG_DATABASE}.payroll_register (
  employee_id STRING NOT NULL COMMENT 'FK to employee_master.employee_id.',
  pay_run_id STRING NOT NULL COMMENT 'Identifier for the payroll run that produced this line.',
  pay_period STRING NOT NULL COMMENT 'Pay period this line applies to, expressed as year-month; on a retro line this is the original period, not the period of payment.',
  pay_date STRING NOT NULL COMMENT 'Date payment was issued, as an ISO-8601 string.',
  run_type STRING NOT NULL COMMENT 'Type of payroll run, such as regular, off-cycle or correction.',
  lohnart_code STRING NOT NULL COMMENT 'FK to pay_component_reference.lohnart_code; wage type code.',
  component_name STRING NOT NULL COMMENT 'Human-readable pay component name.',
  gl_account STRING NOT NULL COMMENT 'GL account this line posts to.',
  cost_center_code STRING NOT NULL COMMENT 'Cost center as booked for this pay period, not the employee's current cost center; required for correct mid-period transfer attribution.',
  location_code STRING NOT NULL COMMENT 'FK to location_reference.location_code; location as of this pay period.',
  bearer STRING NOT NULL COMMENT 'Whether this component is borne by the employer or the employee.',
  amount_eur DECIMAL(14,2) NOT NULL COMMENT 'Monetary amount for this pay component line.',
  assessment_base_eur DECIMAL(14,2) COMMENT 'Base amount this component's contribution or tax was calculated against; null where not applicable to the component type.',
  quantity DECIMAL(12,4) COMMENT 'Quantity basis for the component, such as hours; null for flat-amount components.',
  rate DECIMAL(12,6) COMMENT 'Rate applied to quantity to derive amount_eur; null for flat-amount components.'
)
USING iceberg
PARTITIONED BY (pay_date)
TBLPROPERTIES (
  'format-version' = '2',
  'write.parquet.compression-codec' = 'zstd'
);
