# test_write.py -- generated by pipeline-automator scaffold (project init)
# Exercises the shared pipeline/write.py directly, against tables this file creates
# itself via literal DDL -- write() never creates a table, so these tests own that step
# the way the real generated catalog DDL (infra/catalog/) does for a deployed job.

from __future__ import annotations

from datetime import date
from decimal import Decimal
from typing import TYPE_CHECKING

import pytest

from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

if TYPE_CHECKING:
    from pyspark.sql import SparkSession

# payroll_pipeline.pipeline.write imports pyspark at module level, so importing `write`
# itself is deferred to inside each test function -- collecting this file, and running
# any test that doesn't request `spark`, must never require pyspark to be installed.

_SCHEMA = [
    {"name": "id", "type": "string"},
    {"name": "amount", "type": "decimal(10,2)"},
    {"name": "event_date", "type": "date"},
]

_REORDERED_SCHEMA = [
    {"name": "event_date", "type": "date"},
    {"name": "id", "type": "string"},
    {"name": "amount", "type": "decimal(10,2)"},
]


def _create_table(
    spark: SparkSession, table: str, *, partitioned: bool = False, not_null_id: bool = False
) -> None:
    """Create an empty Iceberg table matching `_SCHEMA`, for `write()` to write into."""
    id_column = "id STRING NOT NULL" if not_null_id else "id STRING"
    ddl = f"CREATE TABLE {table} ({id_column}, amount DECIMAL(10,2), event_date DATE) USING iceberg"
    if partitioned:
        ddl += " PARTITIONED BY (event_date)"
    spark.sql(ddl)


@pytest.mark.integration
def test_write_append_round_trips_rows(spark: SparkSession) -> None:
    from payroll_pipeline.pipeline.write import write

    table = "integration_test.write_append"
    _create_table(spark, table)
    df = synthetic_frame_for(spark, _SCHEMA, [("o1", Decimal("10.00"), date(2024, 1, 1))])

    write(spark, df, table, "append")

    rows = spark.table(table).collect()
    assert len(rows) == 1
    assert rows[0].id == "o1"
    assert rows[0].amount == Decimal("10.00")
    assert rows[0].event_date == date(2024, 1, 1)


@pytest.mark.integration
def test_write_append_twice_doubles_row_count(spark: SparkSession) -> None:
    """Current behavior, not the desired one -- gap 5.4.13. `append` really does append,
    even for a row that already exists; this flips once a `merge` write mode lands (R2)."""
    from payroll_pipeline.pipeline.write import write

    table = "integration_test.write_append_twice"
    _create_table(spark, table)
    df = synthetic_frame_for(spark, _SCHEMA, [("o1", Decimal("10.00"), date(2024, 1, 1))])

    write(spark, df, table, "append")
    write(spark, df, table, "append")

    assert spark.table(table).count() == 2


@pytest.mark.integration
def test_write_overwrite_all_twice_yields_the_same_count(spark: SparkSession) -> None:
    from payroll_pipeline.pipeline.write import write

    table = "integration_test.write_overwrite_all"
    _create_table(spark, table)
    df = synthetic_frame_for(
        spark,
        _SCHEMA,
        [
            ("o1", Decimal("10.00"), date(2024, 1, 1)),
            ("o2", Decimal("20.00"), date(2024, 1, 2)),
        ],
    )

    write(spark, df, table, "overwrite_all")
    write(spark, df, table, "overwrite_all")

    assert spark.table(table).count() == 2


@pytest.mark.integration
def test_write_overwrite_partitions_replaces_only_present_partitions(spark: SparkSession) -> None:
    from payroll_pipeline.pipeline.write import write

    table = "integration_test.write_overwrite_partitions"
    _create_table(spark, table, partitioned=True)
    initial = synthetic_frame_for(
        spark,
        _SCHEMA,
        [
            ("jan1", Decimal("1.00"), date(2024, 1, 1)),
            ("jan2", Decimal("2.00"), date(2024, 1, 2)),
        ],
    )
    write(spark, initial, table, "overwrite_partitions")

    replacement = synthetic_frame_for(
        spark, _SCHEMA, [("jan1_v2", Decimal("9.00"), date(2024, 1, 1))]
    )
    write(spark, replacement, table, "overwrite_partitions")

    rows = {row.id: row.event_date for row in spark.table(table).collect()}
    assert rows == {"jan1_v2": date(2024, 1, 1), "jan2": date(2024, 1, 2)}


@pytest.mark.integration
def test_write_with_columns_in_a_different_order_still_writes_correctly(
    spark: SparkSession,
) -> None:
    """Regression test for gap 5.4.12. Iceberg's `DataFrameWriterV2` binds columns by
    name, not position -- under the old `insertInto`-based writer this would have
    silently mis-mapped every column."""
    from payroll_pipeline.pipeline.write import write

    table = "integration_test.write_column_order"
    _create_table(spark, table)
    df = synthetic_frame_for(spark, _REORDERED_SCHEMA, [(date(2024, 1, 1), "o1", Decimal("10.00"))])

    write(spark, df, table, "append")

    row = spark.table(table).collect()[0]
    assert row.id == "o1"
    assert row.amount == Decimal("10.00")
    assert row.event_date == date(2024, 1, 1)


@pytest.mark.integration
def test_write_null_in_not_null_column_fails(spark: SparkSession) -> None:
    from payroll_pipeline.pipeline.write import write

    table = "integration_test.write_not_null"
    _create_table(spark, table, not_null_id=True)
    df = synthetic_frame_for(spark, _SCHEMA, [(None, Decimal("10.00"), date(2024, 1, 1))])

    with pytest.raises(Exception):  # noqa: B017 -- the exact Spark/JVM exception type varies
        write(spark, df, table, "append")
