# test_read.py -- generated by pipeline-automator scaffold (project init)
# Exercises the shared pipeline/read.py directly, against tables this file creates and
# seeds itself, rather than any specific job's schema -- read() is generic per-source
# infrastructure every job's run() calls with job-specific SourceConfig entries.

from __future__ import annotations

from datetime import date, datetime
from typing import TYPE_CHECKING

import pytest

from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

if TYPE_CHECKING:
    from pyspark.sql import SparkSession

    from payroll_pipeline.runtime.job_settings import SourceConfig

# payroll_pipeline.pipeline.read and .runtime.job_settings both import pyspark at
# module level, so importing `read`/`SourceConfig` themselves is deferred to inside each
# test function -- collecting this file, and running any test that doesn't request
# `spark`, must never require pyspark to be installed.

_SCHEMA = [
    {"name": "id", "type": "string"},
    {"name": "event_date", "type": "date"},
]


def _seed(spark: SparkSession, table: str, rows: list[tuple[str, str]]) -> None:
    """Create an Iceberg table matching `_SCHEMA` and append `rows` to it."""
    spark.sql(f"CREATE TABLE IF NOT EXISTS {table} (id STRING, event_date DATE) USING iceberg")
    synthetic_frame_for(spark, _SCHEMA, rows).writeTo(table).append()


def _source(
    alias: str,
    table: str,
    *,
    partition_column: str | None,
    allow_empty: bool,
    partition_column_type: str | None = None,
    columns: tuple[str, ...] = (),
    contact: str = "data-eng@example.com",
    layer: str | None = None,
    dataset: str | None = None,
) -> SourceConfig:
    """Build a `SourceConfig` with an already-resolved `table_identity`.

    `table_identity` always carries the source's final table identity directly -- these
    tests exercise `read()` in isolation, after the owned/external resolution
    `runtime/run.py` normally performs. `layer`/`dataset` default to `None` (external-style)
    but a test asserting the owned-source error message passes them explicitly, since
    `read()`'s drift check uses `layer is not None` to pick which remedy to name.
    """
    from payroll_pipeline.runtime.job_settings import SourceConfig

    return SourceConfig(
        alias=alias,
        layer=layer,
        dataset=dataset,
        table_identity=table,
        partition_column=partition_column,
        partition_column_type=partition_column_type,
        columns=columns,
        contact=contact,
        allow_empty=allow_empty,
    )


@pytest.mark.integration
def test_read_window_is_half_open(spark: SparkSession) -> None:
    """[start_date, end_date) -- inclusive of start_date, exclusive of end_date."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_window"
    _seed(
        spark,
        table,
        [
            ("before", "2024-01-01"),
            ("in_window", "2024-01-02"),
            ("at_end", "2024-01-03"),
        ],
    )
    source = _source(
        "events",
        table,
        partition_column="event_date",
        partition_column_type="date",
        allow_empty=False,
    )

    result = read(spark, "2024-01-02", "2024-01-03", (source,))

    assert {row.id for row in result["events"].collect()} == {"in_window"}


@pytest.mark.integration
def test_read_with_no_partition_column_reads_the_whole_table(spark: SparkSession) -> None:
    """`partition_column: None` applies no window filter at all."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_unfiltered"
    _seed(spark, table, [("a", "2020-01-01"), ("b", "2030-01-01")])
    source = _source("events", table, partition_column=None, allow_empty=False)

    result = read(spark, "2024-01-01", "2024-01-02", (source,))

    assert result["events"].count() == 2


@pytest.mark.integration
def test_read_empty_window_raises_by_default(spark: SparkSession) -> None:
    """`allow_empty: false` on an empty windowed read fails, naming the alias and window."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_empty_disallowed"
    _seed(spark, table, [("outside", "2020-01-01")])
    source = _source(
        "events",
        table,
        partition_column="event_date",
        partition_column_type="date",
        allow_empty=False,
    )

    with pytest.raises(ValueError) as exc_info:
        read(spark, "2024-01-02", "2024-01-03", (source,))

    message = str(exc_info.value)
    assert "events" in message
    assert "2024-01-02" in message
    assert "2024-01-03" in message


@pytest.mark.integration
def test_read_empty_window_allowed_returns_empty_frame_with_correct_schema(
    spark: SparkSession,
) -> None:
    """`allow_empty: true` returns an empty frame with the table's schema, not a raise."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_empty_allowed"
    _seed(spark, table, [("outside", "2020-01-01")])
    source = _source(
        "events",
        table,
        partition_column="event_date",
        partition_column_type="date",
        allow_empty=True,
    )

    result = read(spark, "2024-01-02", "2024-01-03", (source,))

    assert result["events"].count() == 0
    assert [f.name for f in result["events"].schema.fields] == ["id", "event_date"]


@pytest.mark.integration
def test_read_returns_a_dict_keyed_by_alias(spark: SparkSession) -> None:
    """Multiple sources come back as one dict, keyed by each source's own alias."""
    from payroll_pipeline.pipeline.read import read

    orders_table = "integration_test.read_multi_orders"
    customers_table = "integration_test.read_multi_customers"
    _seed(spark, orders_table, [("o1", "2024-01-01")])
    _seed(spark, customers_table, [("c1", "2024-01-01")])
    sources = (
        _source("orders", orders_table, partition_column=None, allow_empty=False),
        _source("customers", customers_table, partition_column=None, allow_empty=False),
    )

    result = read(spark, "2024-01-01", "2024-01-02", sources)

    assert set(result) == {"orders", "customers"}


# ---------------------------------------------------------------------------
# B2 -- window bound cast to the partition column's declared type
# ---------------------------------------------------------------------------

_WINDOW_CAST_CASES: list[tuple[str, str, tuple[object, object, object]]] = [
    ("date", "DATE", (date(2024, 1, 1), date(2024, 1, 2), date(2024, 1, 3))),
    ("timestamp", "TIMESTAMP", (datetime(2024, 1, 1), datetime(2024, 1, 2), datetime(2024, 1, 3))),
    ("string", "STRING", ("2024-01-01", "2024-01-02", "2024-01-03")),
]


@pytest.mark.integration
@pytest.mark.parametrize(("column_type", "sql_type", "values"), _WINDOW_CAST_CASES)
def test_read_window_bound_is_cast_to_declared_type(
    spark: SparkSession,
    column_type: str,
    sql_type: str,
    values: tuple[object, object, object],
) -> None:
    """A row exactly at start_date is included, one exactly at end_date is excluded --
    for a `date`, a `timestamp`, and a `yyyy-MM-dd` `string` partition column alike.

    This is the regression test for the original defect: a bare string comparison is
    only correct against a string column, and silently returns the wrong window (or none
    at all) against a `date`/`timestamp` column depending on how Spark happens to coerce it.
    """
    from payroll_pipeline.pipeline.read import read

    table = f"integration_test.read_window_cast_{column_type}"
    before, at_start, at_end = values
    spark.sql(f"CREATE TABLE IF NOT EXISTS {table} (id STRING, event_col {sql_type}) USING iceberg")
    spark.createDataFrame(
        [("before", before), ("in_window", at_start), ("at_end", at_end)],
        f"id STRING, event_col {sql_type}",
    ).writeTo(table).append()
    source = _source(
        "events",
        table,
        partition_column="event_col",
        partition_column_type=column_type,
        allow_empty=False,
    )

    result = read(spark, "2024-01-02", "2024-01-03", (source,))

    assert {row.id for row in result["events"].collect()} == {"in_window"}


# ---------------------------------------------------------------------------
# B3 -- contract-versus-observed schema drift, and B4 -- column pruning
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_read_missing_declared_column_raises_naming_contact_for_external_source(
    spark: SparkSession,
) -> None:
    """A missing declared column is fatal; an external source's message names its contact."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_drift_missing_external"
    _seed(spark, table, [("a", "2024-01-01")])
    source = _source(
        "events",
        table,
        partition_column=None,
        allow_empty=False,
        columns=("id:string", "event_date:date", "status:string"),
        contact="crm-team@example.com",
    )

    with pytest.raises(ValueError) as exc_info:
        read(spark, "2024-01-01", "2024-01-02", (source,))

    message = str(exc_info.value)
    assert "status" in message
    assert "crm-team@example.com" in message


@pytest.mark.integration
def test_read_missing_declared_column_raises_naming_regenerate_job_for_owned_source(
    spark: SparkSession,
) -> None:
    """An owned source's drift message points at re-running `generate create-job`."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_drift_missing_owned"
    _seed(spark, table, [("a", "2024-01-01")])
    source = _source(
        "events",
        table,
        partition_column=None,
        allow_empty=False,
        columns=("id:string", "event_date:date", "status:string"),
        layer="processed",
        dataset="clean_orders",
    )

    with pytest.raises(ValueError) as exc_info:
        read(spark, "2024-01-01", "2024-01-02", (source,))

    message = str(exc_info.value)
    assert "status" in message
    assert "generate create-job clean_orders" in message


@pytest.mark.integration
def test_read_retyped_declared_column_raises(spark: SparkSession) -> None:
    """A declared column present with the wrong observed type is fatal, same as missing."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_drift_retyped"
    _seed(spark, table, [("a", "2024-01-01")])
    # event_date is really `date`, declared here as `string` -- a type mismatch.
    source = _source(
        "events",
        table,
        partition_column=None,
        allow_empty=False,
        columns=("id:string", "event_date:string"),
    )

    with pytest.raises(ValueError) as exc_info:
        read(spark, "2024-01-01", "2024-01-02", (source,))

    assert "event_date" in str(exc_info.value)


@pytest.mark.integration
def test_read_extra_undeclared_column_is_fine(spark: SparkSession) -> None:
    """A column present in the table but not declared in `columns` is not an error."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_drift_extra"
    _seed(spark, table, [("a", "2024-01-01")])
    source = _source(
        "events", table, partition_column=None, allow_empty=False, columns=("id:string",)
    )

    result = read(spark, "2024-01-01", "2024-01-02", (source,))

    assert result["events"].count() == 1


@pytest.mark.integration
def test_read_prunes_to_declared_columns(spark: SparkSession) -> None:
    """The returned frame carries exactly the declared columns, not every column read."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_pruning"
    _seed(spark, table, [("a", "2024-01-01")])
    source = _source(
        "events", table, partition_column=None, allow_empty=False, columns=("id:string",)
    )

    result = read(spark, "2024-01-01", "2024-01-02", (source,))

    assert [f.name for f in result["events"].schema.fields] == ["id"]


@pytest.mark.integration
def test_read_with_no_declared_columns_skips_drift_check_and_pruning(spark: SparkSession) -> None:
    """`columns: ()` (a schema-less external source) is not checked or pruned at all."""
    from payroll_pipeline.pipeline.read import read

    table = "integration_test.read_no_declared_columns"
    _seed(spark, table, [("a", "2024-01-01")])
    source = _source("events", table, partition_column=None, allow_empty=False, columns=())

    result = read(spark, "2024-01-01", "2024-01-02", (source,))

    assert [f.name for f in result["events"].schema.fields] == ["id", "event_date"]
