# test_validate.py -- generated by pipeline-automator scaffold (project init)
# Exercises the shared pipeline/validate.py directly, against a real Iceberg sink table
# this file creates itself and a real sink contract written into a throwaway importable
# package -- validate() reads the contract via importlib.resources, exactly as it would
# under Glue, so a test contract has to be a real package too, not a bare dict.

from __future__ import annotations

import importlib
import itertools
from datetime import date
from decimal import Decimal
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest
import yaml

if TYPE_CHECKING:
    from collections.abc import Callable

    from pyspark.sql import SparkSession

# payroll_pipeline.pipeline.validate imports pyspark at module level, so importing
# `validate` itself is deferred to inside each test function -- collecting this file, and
# running any test that doesn't request `spark`, must never require pyspark to be installed.

_ORDER_SCHEMA = [
    {"name": "order_id", "type": "string"},
    {"name": "amount", "type": "decimal(10,2)"},
    {"name": "order_date", "type": "date"},
]

_contract_counter = itertools.count()


@pytest.fixture
def write_contract(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> Callable[..., tuple[str, str]]:
    """Write a sink contract into a fresh, importable throwaway package.

    A uniquely-numbered package name per call avoids `sys.modules` caching collisions
    between tests in the same session -- `importlib.resources` resolves through the
    normal import system, so the package has to actually be importable, not just a file
    on disk.
    """

    def _write(contract: dict[str, Any], contract_name: str = "clean_orders") -> tuple[str, str]:
        package_name = f"_validate_test_contracts_{next(_contract_counter)}"
        pkg_dir = tmp_path / package_name
        pkg_dir.mkdir()
        (pkg_dir / "__init__.py").write_text("", encoding="utf-8")
        (pkg_dir / f"{contract_name}_data_contract.yaml").write_text(
            yaml.safe_dump({"contract": contract}), encoding="utf-8"
        )
        monkeypatch.syspath_prepend(str(tmp_path))
        importlib.invalidate_caches()
        return package_name, contract_name

    return _write


def _order_contract(**overrides: Any) -> dict[str, Any]:
    contract: dict[str, Any] = {
        "name": "clean_orders",
        "layer": "processed",
        "dataset": "clean_orders",
        "grain": {"unique_key": ["order_id"]},
        "schema": [
            {"name": "order_id", "type": "string"},
            {"name": "amount", "type": "decimal(10,2)"},
            {"name": "order_date", "type": "date"},
        ],
    }
    contract.update(overrides)
    return contract


def _create_sink_table(spark: SparkSession, table: str) -> None:
    spark.sql(
        f"CREATE TABLE {table} (order_id STRING, amount DECIMAL(10,2), order_date DATE) "
        "USING iceberg"
    )


@pytest.mark.integration
def test_validate_clean_output_passes_every_check(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_clean"
    _create_sink_table(spark, table)
    package, name = write_contract(_order_contract())
    df = synthetic_frame_for(
        spark,
        _ORDER_SCHEMA,
        [
            ("o1", Decimal("10.00"), date(2024, 1, 1)),
            ("o2", Decimal("20.00"), date(2024, 1, 2)),
        ],
    ).cache()

    result = validate(spark, df, table=table, contract_package=package, contract_name=name)

    assert result.ok
    assert all(c.status in ("passed", "skipped") for c in result.checks)


@pytest.mark.integration
def test_validate_duplicate_grain_keys_fails_with_true_count(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_duplicates"
    _create_sink_table(spark, table)
    package, name = write_contract(_order_contract())
    df = synthetic_frame_for(
        spark,
        _ORDER_SCHEMA,
        [
            ("o1", Decimal("10.00"), date(2024, 1, 1)),
            ("o1", Decimal("10.00"), date(2024, 1, 1)),
            ("o2", Decimal("20.00"), date(2024, 1, 2)),
        ],
    ).cache()

    result = validate(spark, df, table=table, contract_package=package, contract_name=name)

    assert not result.ok
    grain_check = next(c for c in result.checks if c.name == "grain_unique")
    assert grain_check.status == "failed"
    assert grain_check.observed["duplicates"] == 1
    assert grain_check.observed["null_grain_rows"] == 0


@pytest.mark.integration
def test_validate_null_grain_key_fails_separately_from_duplicates(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    """The `count_distinct` trap `validate.py`'s own docstring guards against: without
    the explicit null-row count, a null grain key would deflate the distinct count and
    the uniqueness check would pass on a frame with no usable key at all."""
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_null_grain"
    _create_sink_table(spark, table)
    package, name = write_contract(_order_contract())
    df = synthetic_frame_for(
        spark,
        _ORDER_SCHEMA,
        [
            ("o1", Decimal("10.00"), date(2024, 1, 1)),
            (None, Decimal("20.00"), date(2024, 1, 2)),
        ],
    ).cache()

    result = validate(spark, df, table=table, contract_package=package, contract_name=name)

    assert not result.ok
    grain_check = next(c for c in result.checks if c.name == "grain_unique")
    assert grain_check.status == "failed"
    assert grain_check.observed["duplicates"] == 0
    assert grain_check.observed["null_grain_rows"] == 1


@pytest.mark.integration
def test_validate_value_below_min_fails_with_violation_count(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_min"
    _create_sink_table(spark, table)
    contract = _order_contract(
        schema=[
            {"name": "order_id", "type": "string"},
            {"name": "amount", "type": "decimal(10,2)", "constraints": {"min": 0}},
            {"name": "order_date", "type": "date"},
        ]
    )
    package, name = write_contract(contract)
    df = synthetic_frame_for(
        spark,
        _ORDER_SCHEMA,
        [
            ("o1", Decimal("10.00"), date(2024, 1, 1)),
            ("o2", Decimal("-5.00"), date(2024, 1, 2)),
        ],
    ).cache()

    result = validate(spark, df, table=table, contract_package=package, contract_name=name)

    assert not result.ok
    constraint_check = next(c for c in result.checks if c.name == "constraint_min:amount")
    assert constraint_check.status == "failed"
    assert constraint_check.observed["violations"] == 1


@pytest.mark.integration
def test_validate_output_missing_contract_column_fails_naming_it(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_missing_column"
    _create_sink_table(spark, table)
    package, name = write_contract(_order_contract())
    narrow_schema = [{"name": "order_id", "type": "string"}]
    df = synthetic_frame_for(spark, narrow_schema, [("o1",)]).cache()

    result = validate(spark, df, table=table, contract_package=package, contract_name=name)

    assert not result.ok
    frame_check = next(c for c in result.checks if c.name == "output_matches_contract")
    assert frame_check.status == "failed"
    assert "amount" in frame_check.observed["missing"]
    assert "order_date" in frame_check.observed["missing"]


@pytest.mark.integration
def test_validate_sink_table_missing_column_names_catalog_apply_as_the_fix(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    """Additive drift -- the table lacks a column the contract declares -- is exactly
    what `make catalog-apply` fixes (`ALTER TABLE ... ADD COLUMNS`), so the failure
    message must point there."""
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_drift_additive"
    spark.sql(f"CREATE TABLE {table} (order_id STRING, amount DECIMAL(10,2)) USING iceberg")
    package, name = write_contract(_order_contract())
    df = synthetic_frame_for(
        spark, _ORDER_SCHEMA, [("o1", Decimal("10.00"), date(2024, 1, 1))]
    ).cache()

    result = validate(spark, df, table=table, contract_package=package, contract_name=name)

    assert not result.ok
    table_check = next(c for c in result.checks if c.name == "sink_table_matches_contract")
    assert table_check.status == "failed"
    assert "catalog-apply" in table_check.detail
    assert "will not drop or retype" not in table_check.detail


@pytest.mark.integration
def test_validate_sink_table_retyped_column_does_not_recommend_catalog_apply(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    """A type change on a shared column is refused by `catalog-apply` -- recommending
    it here would send the operator in a circle."""
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_drift_retyped"
    spark.sql(
        f"CREATE TABLE {table} (order_id STRING, amount DECIMAL(18,4), order_date DATE) "
        "USING iceberg"
    )
    package, name = write_contract(_order_contract())
    df = synthetic_frame_for(
        spark, _ORDER_SCHEMA, [("o1", Decimal("10.00"), date(2024, 1, 1))]
    ).cache()

    result = validate(spark, df, table=table, contract_package=package, contract_name=name)

    assert not result.ok
    table_check = next(c for c in result.checks if c.name == "sink_table_matches_contract")
    assert table_check.status == "failed"
    assert "will not drop or retype" in table_check.detail


@pytest.mark.integration
def test_validate_enum_ref_is_skipped_and_does_not_fail_validation(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_enum_ref"
    _create_sink_table(spark, table)
    contract = _order_contract(
        schema=[
            {"name": "order_id", "type": "string"},
            {
                "name": "amount",
                "type": "decimal(10,2)",
                "constraints": {"enum_ref": "amount_tiers"},
            },
            {"name": "order_date", "type": "date"},
        ]
    )
    package, name = write_contract(contract)
    df = synthetic_frame_for(
        spark, _ORDER_SCHEMA, [("o1", Decimal("10.00"), date(2024, 1, 1))]
    ).cache()

    result = validate(spark, df, table=table, contract_package=package, contract_name=name)

    assert result.ok
    enum_check = next(c for c in result.checks if c.name == "constraint_enum:amount")
    assert enum_check.status == "skipped"


@pytest.mark.integration
def test_validate_triggers_exactly_one_spark_job(
    spark: SparkSession, write_contract: Callable[..., tuple[str, str]]
) -> None:
    """Regression guard: every data check is folded into a single aggregation, so one
    `validate()` call must cost exactly one Spark job -- not one job per check."""
    from payroll_pipeline.pipeline.validate import validate
    from payroll_pipeline.tests._schema_fixtures import synthetic_frame_for

    table = "integration_test.validate_one_job"
    _create_sink_table(spark, table)
    contract = _order_contract(
        schema=[
            {"name": "order_id", "type": "string"},
            {"name": "amount", "type": "decimal(10,2)", "constraints": {"min": 0, "max": 1000}},
            {"name": "order_date", "type": "date"},
        ]
    )
    package, name = write_contract(contract)
    df = synthetic_frame_for(
        spark, _ORDER_SCHEMA, [("o1", Decimal("10.00"), date(2024, 1, 1))]
    ).cache()

    job_group = "test_validate_triggers_exactly_one_spark_job"
    spark.sparkContext.setJobGroup(job_group, "validate() job-count regression guard")
    try:
        validate(spark, df, table=table, contract_package=package, contract_name=name)
        job_ids = spark.sparkContext.statusTracker().getJobIdsForGroup(job_group)
    finally:
        spark.sparkContext.setJobGroup("", "")

    assert len(job_ids) == 1, f"expected exactly one Spark job, got {len(job_ids)}: {job_ids}"
