# modules/iam/variables.tf -- generated by pipeline-automator scaffold (project init)

variable "name_prefix" {
  description = "Prefix applied to IAM resource names (typically '<data_product>-<environment>')."
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "aws_region" {
  description = "AWS region the Glue Catalog resources referenced below live in."
  type        = string
}

variable "catalog_database_arns" {
  description = "ARNs of the Glue Catalog databases the Glue execution role may read from and commit Iceberg table updates to. Never grants glue:CreateTable -- table creation belongs to a separate deployer identity, not the job's own role."
  type        = list(string)
}

variable "raw_bucket_arn" {
  description = "ARN of the raw layer S3 bucket. Glue is granted read-only access."
  type        = string
}

variable "preprocessed_bucket_arn" {
  description = "ARN of the preprocessed layer S3 bucket. Glue is granted read-write access."
  type        = string
}

variable "processed_bucket_arn" {
  description = "ARN of the processed layer S3 bucket. Glue is granted read-write access."
  type        = string
}

variable "scripts_bucket_arn" {
  description = "ARN of the scripts S3 bucket. Glue is granted read-only access to fetch job scripts."
  type        = string
}

variable "tags" {
  description = "Tags applied to all resources in this module."
  type        = map(string)
  default     = {}
}
