"""Scaffold-owned runtime settings and run-record emission for every ETL job.

Generated by pipeline-automator scaffold (project init). Edit the scaffold
template, not this file.

This module is the single place where a job's runtime inputs are resolved:
Glue job arguments, the processing window, and the SparkSession. Per-job
modules never parse arguments themselves -- they open `job_run()` and receive
an immutable `JobContext` plus the mutable `RunRecord` for that execution.

All dates are handled in UTC. Glue workers run in UTC regardless of where the
job was authored, so deriving the default window from local time would make
the same job process different data depending on who triggered it.

Two deliberate omissions, decided rather than overlooked:
    * No `GlueContext` / `DynamicFrame`. Every read and write in this package
      uses the plain Spark SQL API, so the Glue wrapper layer buys nothing.
    * No `Job.init()` / `Job.commit()`. Those exist to drive Glue job
      bookmarks. The processing window is resolved explicitly here and applied
      by `read()`, so bookmarks would duplicate -- and eventually contradict --
      that logic. The absence of `job.commit()` is intentional.
"""

from __future__ import annotations

import json
import sys
import time
import traceback
from argparse import ArgumentParser
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import asdict, dataclass, field
from datetime import UTC, date, datetime, timedelta
from typing import Any

from pyspark.sql import SparkSession

DATE_FORMAT = "%Y-%m-%d"
RUN_RECORD_PREFIX = "RUN_RECORD"

#: Arguments this package understands. All are optional: Glue supplies the
#: JOB_* pair automatically, and an absent window means "process yesterday".
_OPTIONAL_ARGS = (
    "JOB_NAME",
    "JOB_RUN_ID",
    "start_date",
    "end_date",
    "environment",
    "catalog_database_prefix",
)


# --- argument resolution ---------------------------------------------------


def _resolve_args(argv: list[str]) -> dict[str, str]:
    """Resolve job arguments, whether running under Glue or locally.

    `getResolvedOptions` raises when asked for a name that is absent from
    argv, so optional arguments are filtered down to the ones actually
    supplied before the call. `awsglue` exists only inside the Glue runtime,
    so local runs, tests, mypy, and CI take the argparse path instead.
    """
    supplied = [name for name in _OPTIONAL_ARGS if f"--{name}" in argv]
    try:
        from awsglue.utils import getResolvedOptions  # type: ignore[import-not-found]
    except ImportError:
        return _resolve_args_locally(argv)
    resolved: dict[str, str] = getResolvedOptions(argv, supplied)
    return resolved


def _resolve_args_locally(argv: list[str]) -> dict[str, str]:
    """Parse the same arguments outside Glue, ignoring Glue's own reserved flags."""
    parser = ArgumentParser(allow_abbrev=False)
    for name in _OPTIONAL_ARGS:
        parser.add_argument(f"--{name}")
    namespace, _unknown = parser.parse_known_args(argv[1:])
    return {key: value for key, value in vars(namespace).items() if value is not None}


# --- window resolution -----------------------------------------------------


def resolve_window(
    start_date: str | None,
    end_date: str | None,
    *,
    reference_date: date | None = None,
) -> tuple[str, str]:
    """Resolve the half-open processing window [start_date, end_date).

    Pure and side-effect free: given the same three inputs it always returns
    the same window, with no clock, no Spark, and no AWS involved.

    A defaulted window never extends past `reference_date`. The current day is
    still accumulating, so a window ending after it would process a partial
    day and record it as a complete one.

    Args:
        start_date: Inclusive lower bound, `YYYY-MM-DD`, or None.
        end_date: Exclusive upper bound, `YYYY-MM-DD`, or None.
        reference_date: The date "now" means for this run. Defaults to the
            current UTC date. Pass it explicitly to derive the window from a
            schedule time rather than wall-clock time, and in tests.

    Returns:
        The resolved (start_date, end_date) pair as `YYYY-MM-DD` strings.

    Rules:
        neither supplied -> yesterday, i.e. [reference - 1 day, reference)
        start only       -> a single day, capped at the reference date
        end only         -> rejected, the intended span is ambiguous
        both supplied    -> used as given, including a future end date

    Raises:
        ValueError: On an unparseable date, an end-only window, a start date
            in the future, a start date with no complete day left to process,
            or a window whose end is not strictly after its start.
    """
    reference = reference_date or datetime.now(UTC).date()

    if start_date is None and end_date is None:
        start = reference - timedelta(days=1)
        return start.strftime(DATE_FORMAT), reference.strftime(DATE_FORMAT)

    if start_date is None:
        raise ValueError(
            "--end_date was supplied without --start_date; the intended window span "
            "is ambiguous. Supply both, or neither to process yesterday."
        )

    start = _parse_date(start_date, "--start_date")

    if start > reference:
        raise ValueError(
            f"--start_date={start:%Y-%m-%d} is in the future relative to the reference "
            f"date {reference:%Y-%m-%d}; there is no data to process."
        )

    if end_date is not None:
        end = _parse_date(end_date, "--end_date")
    else:
        # A single day, but never past the reference date: [today, tomorrow)
        # would silently process a day that has not finished happening.
        end = min(start + timedelta(days=1), reference)
        if end <= start:
            raise ValueError(
                f"--start_date={start:%Y-%m-%d} is not before the reference date "
                f"{reference:%Y-%m-%d}, and no --end_date was supplied. The default "
                "window stops at the reference date, so there is no complete day to "
                "process. Wait for the day to close, or pass --end_date explicitly."
            )

    if end <= start:
        raise ValueError(
            f"window end {end:%Y-%m-%d} must be strictly after start {start:%Y-%m-%d}; "
            "the window is half-open [start, end)."
        )
    return start.strftime(DATE_FORMAT), end.strftime(DATE_FORMAT)


def _parse_date(value: str, flag: str) -> date:
    try:
        return datetime.strptime(value, DATE_FORMAT).date()
    except ValueError as exc:
        raise ValueError(f"{flag}={value!r} is not a valid {DATE_FORMAT} date") from exc


# --- Spark session -----------------------------------------------------


def build_spark_session(app_name: str) -> SparkSession:
    """Return the active SparkSession, creating one if this is a local run.

    Under Glue the session already exists and `getOrCreate` adopts it along
    with the catalog configuration Glue installed. The same adoption applies
    in tests: a session-scoped fixture builds a configured local session
    first, so tests exercise this code path rather than a parallel one.

    Hive support is required either way -- `read()` resolves sources via
    `spark.read.table` and `write()` uses `insertInto`, both of which go
    through the metastore.
    """
    return SparkSession.builder.appName(app_name).enableHiveSupport().getOrCreate()


# --- job context -------------------------------------------------------


@dataclass(frozen=True)
class JobContext:
    """Immutable runtime inputs for a single job execution.

    Everything here differs between two runs of the same job. Per-job settings
    that are identical across every run belong in `JobConfig` instead.
    """

    spark: SparkSession
    start_date: str
    end_date: str
    glue_job_name: str | None = None
    glue_run_id: str | None = None
    environment: str | None = None
    catalog_database_prefix: str | None = None

    def table_identity(self, layer: str, dataset: str) -> str:
        """Compose an owned table's two-part `{database}.{dataset}` identity.

        `layer` and `dataset` are rendered into the job script at generation time
        (they carry no deploy-environment information); `catalog_database_prefix`
        carries the environment and is resolved here, at runtime, from the
        `--catalog_database_prefix` Glue job argument Terraform supplies -- never
        baked into the script itself, since the script is rendered once and
        deployed to every environment. Used identically for the job's own sink and
        for every owned source it reads from.

        Args:
            layer: Medallion layer, e.g. "processed".
            dataset: Dataset name within that layer.

        Returns:
            The composed `{catalog_database_prefix}_{layer}.{dataset}` identity.

        Raises:
            ValueError: If `catalog_database_prefix` was not supplied.
        """
        if self.catalog_database_prefix is None:
            raise ValueError(
                "table_identity() requires --catalog_database_prefix, which was not "
                "supplied to this job run."
            )
        return f"{self.catalog_database_prefix}_{layer}.{dataset}"


# --- job config ----------------------------------------------------------


@dataclass(frozen=True)
class SourceConfig:
    """One source's read configuration, fixed at generation time.

    `layer`/`dataset` and `table_identity` are mutually exclusive: an owned source
    carries `layer`/`dataset` (composed into a full identity at runtime by
    `JobContext.table_identity`, since the deploy environment isn't known at
    generation time); an external source carries its `table_identity` verbatim,
    baked in at generation time since it never varies by environment. By the time a
    `SourceConfig` reaches `read()`, `table_identity` has always been resolved --
    `runtime/run.py` does that resolution before calling `read()`.

    `partition_column_type` is `None` exactly when `partition_column` is -- when set, it's
    one of `"date"`/`"timestamp"`/`"string"`, resolved and validated at generation time
    (see `render.py`). `columns` holds the source contract's declared schema as
    `"name:type"` entries, canonicalized at generation time; empty when the contract has
    no schema (external, under the current skeleton), in which case `read()` skips both
    the contract-versus-observed drift check and column pruning.
    """

    alias: str
    layer: str | None
    dataset: str | None
    table_identity: str | None
    partition_column: str | None
    partition_column_type: str | None
    columns: tuple[str, ...]
    contact: str
    allow_empty: bool


@dataclass(frozen=True)
class SinkConfig:
    """Where and how this job writes, fixed at generation time."""

    layer: str
    dataset: str
    write_mode: str


@dataclass(frozen=True)
class JobConfig:
    """Everything about a job that is identical across every run of it."""

    job_name: str
    contract_package: str
    sources: tuple[SourceConfig, ...]
    sink: SinkConfig

    @property
    def contract_name(self) -> str:
        """The sink contract's name, which is always the sink dataset."""
        return self.sink.dataset


def build_context(config: JobConfig) -> JobContext:
    """Resolve arguments, the processing window, and the SparkSession.

    Call this through `job_run()` rather than directly, so that a failure here
    still produces a run record.

    Args:
        config: The job's generation-time-fixed configuration; only
            `config.job_name` is used here, as the Spark application name.
    """
    args = _resolve_args(sys.argv)
    start_date, end_date = resolve_window(args.get("start_date"), args.get("end_date"))
    return JobContext(
        spark=build_spark_session(app_name=config.job_name),
        start_date=start_date,
        end_date=end_date,
        glue_job_name=args.get("JOB_NAME"),
        glue_run_id=args.get("JOB_RUN_ID"),
        environment=args.get("environment"),
        catalog_database_prefix=args.get("catalog_database_prefix"),
    )


# --- run record ----------------------------------------------------------


@dataclass
class RunRecord:
    """One structured summary of a single job execution.

    Mutable by design: `job_run` fills in the outcome fields, `phase` tracks
    which stage is executing, and the job body may attach anything else to
    `metrics`. `start_date` and `end_date` are optional because a failure
    during startup means the window was never resolved -- a record with a null
    window says the job died before it knew what it was meant to process.
    """

    job_name: str
    started_at: str
    status: str = "RUNNING"
    phase: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    glue_job_name: str | None = None
    glue_run_id: str | None = None
    environment: str | None = None
    catalog_database_prefix: str | None = None
    config: dict[str, Any] | None = None
    finished_at: str | None = None
    duration_seconds: float | None = None
    phase_durations: dict[str, float] = field(default_factory=dict)
    error_type: str | None = None
    error_message: str | None = None
    traceback: str | None = None
    metrics: dict[str, Any] = field(default_factory=dict)


@contextmanager
def phase(record: RunRecord, name: str) -> Iterator[None]:
    """Mark which stage of the job is executing, and time it.

    Nothing resets `record.phase` on the way out of a failure, so it still
    names the stage that was running when the exception escaped. `job_run`
    clears it on success, so a non-null phase on an emitted record always
    means "this is where it broke".
    """
    record.phase = name
    started = time.monotonic()
    try:
        yield
    finally:
        record.phase_durations[name] = round(time.monotonic() - started, 3)


@contextmanager
def job_run(config: JobConfig) -> Iterator[tuple[JobContext, RunRecord]]:
    """Build the job context and wrap the run so exactly one record is emitted.

    Context construction happens inside the try block on purpose: an
    unparseable `--start_date`, or a SparkSession that will not start, is
    precisely the kind of failure a record is for. Building the context before
    entering the manager would leave those cases silent.

    On failure the record is completed with the error and emitted, then the
    exception is re-raised unchanged -- swallowing it would leave Glue
    reporting SUCCEEDED for a run that produced nothing.

    Args:
        config: The job's generation-time-fixed configuration for this run.

    Yields:
        The resolved `JobContext` and the mutable `RunRecord` for this run.
    """
    record = RunRecord(job_name=config.job_name, started_at=_utc_now_iso(), config=asdict(config))
    started = time.monotonic()
    try:
        with phase(record, "startup"):
            ctx = build_context(config)
        record.start_date = ctx.start_date
        record.end_date = ctx.end_date
        record.glue_job_name = ctx.glue_job_name
        record.glue_run_id = ctx.glue_run_id
        record.environment = ctx.environment
        record.catalog_database_prefix = ctx.catalog_database_prefix
        yield ctx, record
    except BaseException as exc:
        record.status = "FAILED"
        record.error_type = type(exc).__name__
        record.error_message = str(exc)[:2000]
        record.traceback = traceback.format_exc()[-4000:]
        raise
    else:
        record.status = "SUCCEEDED"
        record.phase = None
    finally:
        record.finished_at = _utc_now_iso()
        record.duration_seconds = round(time.monotonic() - started, 3)
        emit_run_record(record)


def emit_run_record(record: RunRecord) -> None:
    """Write the run record to stdout as a single line of JSON.

    stdout is the whole transport. The Glue jobs set
    `--enable-continuous-cloudwatch-log`, so the driver's stdout streams to
    CloudWatch Logs with no extra wiring, no IAM beyond what the job already
    has, and nothing to fail independently of the job itself.

    The constant prefix makes the record addressable by a CloudWatch metric
    filter or a Logs Insights query without having to parse it out of the
    surrounding Spark noise.

    This record is for humans and observability only. Orchestration keys off
    Glue's own job-run state, which is set by the script's exit code -- which
    is why `job_run` re-raises rather than reporting failure only here.
    """
    payload = json.dumps(asdict(record), default=str, sort_keys=True)
    print(f"{RUN_RECORD_PREFIX} {payload}", flush=True)


def _utc_now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")
