# main.tf -- generated by pipeline-automator scaffold (project init)
# Root module for the payroll_pipeline data pipeline.
#
# Per-job resources (Glue job entries) are appended below the AMEND marker
# by `pipeline-automator scaffold` when an ETL job is created.
# Do not remove the markers -- the amend logic targets them.

locals {
  name_prefix = "${var.data_product}-${var.environment}"
}

# ---------------------------------------------------------------------------
# Foundational, project-wide resources (created once at project init)
# ---------------------------------------------------------------------------

module "s3" {
  source = "./modules/s3"

  name_prefix                        = local.name_prefix
  environment                        = var.environment
  bucket_names                       = var.bucket_names
  lifecycle_rules_enabled            = var.lifecycle_rules_enabled
  noncurrent_version_expiration_days = var.noncurrent_version_expiration_days
  tags                               = var.tags
}

module "catalog" {
  source = "./modules/catalog"

  name_prefix         = local.name_prefix
  environment         = var.environment
  data_product        = var.data_product
  results_bucket_name = module.s3.bucket_names["scripts"]
  tags                = var.tags
}

module "iam" {
  source = "./modules/iam"

  name_prefix             = local.name_prefix
  environment             = var.environment
  aws_region              = var.aws_region
  raw_bucket_arn          = module.s3.bucket_arns["raw"]
  preprocessed_bucket_arn = module.s3.bucket_arns["preprocessed"]
  processed_bucket_arn    = module.s3.bucket_arns["processed"]
  scripts_bucket_arn      = module.s3.bucket_arns["scripts"]
  catalog_database_arns   = values(module.catalog.catalog_database_arns)
  tags                    = var.tags
}

module "glue" {
  source = "./modules/glue"

  name_prefix         = local.name_prefix
  environment         = var.environment
  aws_region          = var.aws_region
  role_arn            = module.iam.glue_execution_role_arn
  scripts_bucket_name = module.s3.bucket_names["scripts"]
  tags                = var.tags

  # ---------------------------------------------------------------------------
  # BEGIN ETL jobs (managed by pipeline-automator -- do not edit by hand)
  # >>> AMEND:JOBS
  jobs = {
    prepare_payroll_register = {
      number_of_workers = 2
      worker_type       = "G.1X"
    }
  }
  # <<< AMEND:JOBS
  # END ETL jobs
  # ---------------------------------------------------------------------------
}
