# outputs.tf -- generated by pipeline-automator scaffold (project init)
# Project-wide outputs for the payroll_pipeline data pipeline.

output "bucket_arns" {
  description = "ARNs of all medallion and scripts S3 buckets for payroll_pipeline."
  value       = module.s3.bucket_arns
}

output "bucket_names" {
  description = "Names of all medallion and scripts S3 buckets for payroll_pipeline."
  value       = module.s3.bucket_names
}

output "glue_execution_role_arn" {
  description = "ARN of the IAM role assumed by Glue jobs in payroll_pipeline."
  value       = module.iam.glue_execution_role_arn
}

output "catalog_database_names" {
  description = "Map of medallion layer to Glue Catalog database name for the Iceberg sink tables of payroll_pipeline."
  value       = module.catalog.catalog_database_names
}

output "glue_job_names" {
  description = "Map of ETL job key to full Glue job name for payroll_pipeline."
  value       = module.glue.job_names
}
