# prod.tfvars -- generated by pipeline-automator scaffold (project init)
# Concrete input values for the payroll_pipeline pipeline in the
# prod environment. Commit this file. Do NOT put secrets here --
# credentials come from AWS_PROFILE / environment, never from tfvars.

aws_region   = "eu-west-1"
environment  = "prod"
data_product = "payroll_pipeline"

bucket_names = {
  raw          = "raw"
  preprocessed = "preprocessed"
  processed    = "processed"
  scripts      = "scripts"
}

tags = {
  DataProduct = "payroll_pipeline"
  Project     = "payroll_pipeline"
  Environment = "prod"
  ManagedBy   = "terraform"
}
