# providers.tf -- generated by pipeline-automator scaffold (project init)
# Provider and backend configuration for the payroll_pipeline data pipeline.

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Partial backend configuration: values come from
  # infra/terraform/backend/{environment}.hcl, supplied at init time --
  #   terraform init -backend-config=backend/dev.hcl
  # A literal `key` here would put every environment in ONE state file: the
  # second environment's apply would read the first's state and plan to rename
  # or destroy every resource in it. Do not reinstate the literals.
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      DataProduct = "payroll_pipeline"
      ManagedBy   = "terraform"
      Project     = "payroll_pipeline"
      Environment = var.environment
    }
  }
}
