# variables.tf -- generated by pipeline-automator scaffold (project init)
# Project-wide input variables for the payroll_pipeline data pipeline.

variable "aws_region" {
  description = "AWS region into which the payroll_pipeline pipeline resources are deployed."
  type        = string
  default     = "eu-west-1"
}

variable "environment" {
  description = "Deployment environment (e.g. dev, staging, prod)."
  type        = string
  default     = "dev"
}

variable "data_product" {
  description = "Name of the data product this pipeline belongs to."
  type        = string
  default     = "payroll_pipeline"
}

variable "bucket_names" {
  description = "Suffixes for the four medallion and scripts S3 buckets. Combined with '<data_product>-<environment>-' to form the full bucket name."
  type        = map(string)
  default = {
    raw          = "raw"
    preprocessed = "preprocessed"
    processed    = "processed"
    scripts      = "scripts"
  }
}

variable "lifecycle_rules_enabled" {
  description = "Whether to enable intelligent-tiering and noncurrent version expiration on all S3 buckets."
  type        = bool
  default     = true
}

variable "noncurrent_version_expiration_days" {
  description = "Days after which noncurrent S3 object versions are expired."
  type        = number
  default     = 90
}

variable "tags" {
  description = "Common tags applied to all resources."
  type        = map(string)
  default = {
    DataProduct = "payroll_pipeline"
    Project     = "payroll_pipeline"
    Environment = "dev"
    ManagedBy   = "terraform"
  }
}
