"""Generated by pipeline-automator scaffold (project init). Loads `<job>_schemas.yaml`
and `<job>.yaml` to build isolated per-transformation schema-check cases, and owns the
schema comparison every `test_{job}_schema.py` file uses.

Rendered once per project, not per job -- keeping this out of the generated per-job
test file is what lets that file stay short and stable across spec changes. Parses raw
YAML rather than importing engineering-automation's Pydantic models: this file ships
inside every generated project, which has no dependency on the scaffolding tool itself.

pyspark imports are deferred to inside the functions that actually construct or inspect
a DataFrame (mirroring `pipeline/types.py`'s `to_spark_type`), so importing this module
-- and calling `transformation_cases`, which only parses YAML -- never requires pyspark
to be installed.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from payroll_pipeline.pipeline.types import normalize, to_spark_type

if TYPE_CHECKING:
    from pyspark.sql import DataFrame, SparkSession
    from pyspark.sql.types import StructType


@dataclass(frozen=True)
class Case:
    """One transformation's isolated schema-check case, built from `<job>_schemas.yaml`."""

    name: str
    inputs: list[str]
    input_schemas: dict[str, list[dict[str, str]]]
    expected: list[dict[str, str]]


def _schema_for(schemas: dict[str, list[dict[str, str]]], name: str) -> list[dict[str, str]]:
    """Resolve one input name to its predicted schema, whether a source alias or a
    transformation result.

    A source alias is present as a bare key in `schemas`; a transformation's output is
    only ever present as `{name}_result` -- never as a bare key -- so the two cannot be
    ambiguous regardless of naming overlap between sources and transformations.
    """
    return schemas[name] if name in schemas else schemas[f"{name}_result"]


def transformation_cases(job_name: str) -> list[Case]:
    """Build one `Case` per transformation, sourced from `{job_name}_schemas.yaml`.

    Reads the job's settings YAML for each transformation's declared `inputs` (order
    matters -- it must match the generated function's positional parameters) and the
    generated schemas YAML for the resolver's predicted schema of every source alias and
    `{transformation}_result`.

    Args:
        job_name: Name of the ETL job, matching its directory name under `jobs/`.

    Returns:
        One `Case` per transformation declared in the job spec, in spec order.
    """
    jobs_dir = Path(__file__).resolve().parent.parent / "jobs" / job_name
    settings = yaml.safe_load((jobs_dir / f"{job_name}.yaml").read_text(encoding="utf-8"))
    schemas_doc = yaml.safe_load(
        (jobs_dir / f"{job_name}_schemas.yaml").read_text(encoding="utf-8")
    )
    schemas = schemas_doc["schemas"]

    return [
        Case(
            name=t["name"],
            inputs=t["inputs"],
            input_schemas={name: _schema_for(schemas, name) for name in t["inputs"]},
            expected=schemas[f"{t['name']}_result"],
        )
        for t in settings["job"]["transformations"]
    ]


def synthetic_frame_for(
    spark: SparkSession, schema: list[dict[str, str]], rows: Sequence[tuple[Any, ...]] = ()
) -> DataFrame:
    """Build a DataFrame with a declared schema and caller-supplied rows.

    The schema is always constructed from the declaration via `to_spark_type`, never
    inferred from `rows` -- inference silently widens `int` to `bigint` and would let a
    fixture diverge from the contract or resolved schema it is meant to represent.

    Args:
        spark: Active SparkSession.
        schema: `[{"name": ..., "type": ...}, ...]`, as found in a data contract or
            `<job>_schemas.yaml`.
        rows: Row tuples in `schema`'s column order. Defaults to no rows, i.e. an
            empty frame with the declared schema.

    Returns:
        A DataFrame with one nullable `StructField` per column, in the given order,
        holding exactly `rows`.
    """
    from pyspark.sql.types import StructField, StructType

    fields = [StructField(c["name"], to_spark_type(c["type"]), nullable=True) for c in schema]
    return spark.createDataFrame(list(rows), StructType(fields))


def empty_frame_for(spark: SparkSession, columns: list[dict[str, str]]) -> DataFrame:
    """Build an empty DataFrame whose schema matches a resolved-schema column list.

    Thin alias for `synthetic_frame_for`'s zero-row case, kept under its own name since
    the generated schema-check test (`test_{etl_job}_schema.py`) imports it directly.

    Args:
        spark: Active SparkSession.
        columns: `[{"name": ..., "type": ...}, ...]`, as found in `<job>_schemas.yaml`.

    Returns:
        An empty DataFrame with one nullable `StructField` per column, in the given order.
    """
    return synthetic_frame_for(spark, columns)


def assert_schema_matches(actual: StructType, expected: list[dict[str, str]]) -> None:
    """Compare by name and type only -- nullability and column order are excluded.

    Nullability: Spark widens it on almost every derived expression, so asserting it
    produces noise, not signal; Iceberg enforces it at write and validate.py checks it
    against real data. Column order: Iceberg binds by name, so order is not a
    correctness property.

    Args:
        actual: The DataFrame schema a transformation function actually returned.
        expected: `[{"name": ..., "type": ...}, ...]`, as found in `<job>_schemas.yaml`.

    Raises:
        AssertionError: Naming every missing column, every unexpected column, and every
            type mismatch (both the actual and expected type), so a failure is legible
            without re-running anything.
    """
    got = {f.name: normalize(f.dataType.simpleString()) for f in actual.fields}
    want = {c["name"]: normalize(c["type"]) for c in expected}

    missing = sorted(set(want) - set(got))
    unexpected = sorted(set(got) - set(want))
    mismatched = {
        name: (got[name], want[name])
        for name in sorted(set(got) & set(want))
        if got[name] != want[name]
    }

    if not (missing or unexpected or mismatched):
        return

    parts = []
    if missing:
        parts.append(f"missing columns: {missing}")
    if unexpected:
        parts.append(f"unexpected columns: {unexpected}")
    if mismatched:
        detail = ", ".join(f"{n}: got {g!r}, want {w!r}" for n, (g, w) in mismatched.items())
        parts.append(f"type mismatches: {detail}")
    raise AssertionError("Schema mismatch -- " + "; ".join(parts))
