#!/usr/bin/env bash
# scripts/apply_catalog.sh -- generated by pipeline-automator scaffold (project init)
#
# Applies every infra/catalog/*.sql file via Athena, substituting ${CATALOG_DATABASE}
# per file from its {layer}__{dataset}.sql filename plus DATA_PRODUCT/ENVIRONMENT.
# CREATE TABLE IF NOT EXISTS makes this idempotent -- safe to run on every deploy,
# unconditionally, step 4 of the deploy sequence documented in README.md (after the
# Terraform apply that creates the catalog databases, before running the job).
#
# CREATE TABLE IF NOT EXISTS is a no-op against an existing table: it does not pick
# up a contract change. This script closes that gap additively only -- a column
# present in the DDL but absent from the live table is added via ALTER TABLE ADD
# COLUMNS. A column removed from the DDL, or one whose type changed, is refused: this
# script never drops or retypes a column. Fix that by hand, or wait for `generate
# migrate` (R4, not yet built).
#
# Requires: aws CLI configured; DATA_PRODUCT, ENVIRONMENT, AWS_REGION set as job
# env: in deploy-{env}.yml's catalog-apply job (step 6 of README.md's Deploying
# sequence) -- .env is for local, manual runs only, never the source of these
# three in the deployed path. An Athena workgroup with a results location
# (created by Terraform's modules/catalog) is also required.

set -euo pipefail

: "${DATA_PRODUCT:?DATA_PRODUCT must be set (see .env.example)}"
: "${ENVIRONMENT:?ENVIRONMENT must be set (see .env.example)}"
: "${AWS_REGION:?AWS_REGION must be set (see .env.example)}"

ATHENA_WORKGROUP="${DATA_PRODUCT}-${ENVIRONMENT}-catalog"
CATALOG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/infra/catalog"

# Runs one Athena query, waits for it to finish, and prints its result rows (if any).
# Fails the script on any state other than SUCCEEDED.
run_query() {
  local statement="$1"
  local query_id state reason
  local max_attempts=180  # 180 * 2s = 6 minutes; Athena DDL/DESCRIBE should never approach this
  local attempt=0

  query_id="$(aws athena start-query-execution \
    --region "$AWS_REGION" \
    --work-group "$ATHENA_WORKGROUP" \
    --query-string "$statement" \
    --query 'QueryExecutionId' \
    --output text)"

  while true; do
    attempt=$((attempt + 1))
    if [ "$attempt" -gt "$max_attempts" ]; then
      echo "Query $query_id did not finish after $max_attempts polls." >&2
      echo "Statement was:" >&2
      echo "$statement" >&2
      exit 1
    fi
    state="$(aws athena get-query-execution \
      --region "$AWS_REGION" \
      --query-execution-id "$query_id" \
      --query 'QueryExecution.Status.State' \
      --output text)"
    case "$state" in
      SUCCEEDED) break ;;
      FAILED | CANCELLED)
        reason="$(aws athena get-query-execution \
          --region "$AWS_REGION" \
          --query-execution-id "$query_id" \
          --query 'QueryExecution.Status.StateChangeReason' \
          --output text)"
        echo "Query failed ($state): $reason" >&2
        echo "Statement was:" >&2
        echo "$statement" >&2
        exit 1
        ;;
      *) sleep 2 ;;
    esac
  done

  aws athena get-query-results \
    --region "$AWS_REGION" \
    --query-execution-id "$query_id" \
    --query 'ResultSet.Rows[1:][].Data[].VarCharValue' \
    --output text
}

# Extracts "name type" pairs (one per line, space-separated, lowercased) from a
# rendered DDL file's column list -- the lines between "CREATE TABLE ... (" and the
# matching ")". Relies on render_catalog_ddl's fixed two-space-indented,
# one-column-per-line shape. Lowercased because Athena's DESCRIBE returns lowercase
# type names, and SQL type keywords are case-insensitive, so comparing both sides
# lowercased avoids a false "retyped" positive on an unchanged column.
ddl_columns() {
  sed -n '/^CREATE TABLE/,/^)/p' "$1" \
    | sed '1d;$d' \
    | sed -E 's/^\s+//; s/,$//; s/ NOT NULL//; s/ COMMENT .*//' \
    | awk '{print $1, $2}' \
    | tr '[:upper:]' '[:lower:]'
}

if [ ! -d "$CATALOG_DIR" ]; then
  echo "No infra/catalog/ directory found; nothing to apply."
  exit 0
fi

shopt -s nullglob
sql_files=("$CATALOG_DIR"/*.sql)
shopt -u nullglob

if [ ${#sql_files[@]} -eq 0 ]; then
  echo "No infra/catalog/*.sql files found; nothing to apply."
  exit 0
fi

for sql_file in "${sql_files[@]}"; do
  filename="$(basename "$sql_file" .sql)"
  layer="${filename%%__*}"
  dataset="${filename#*__}"
  database="${DATA_PRODUCT}_${ENVIRONMENT}_${layer}"

  echo "Applying $sql_file against ${database}.${dataset}..."
  create_statement="$(sed "s/\${CATALOG_DATABASE}/${database}/g" "$sql_file")"
  run_query "$create_statement" >/dev/null

  # Additive drift check: columns in the DDL but not in the live table are added;
  # any other difference (a removed or retyped column) is refused, not attempted.
  # Lowercased for the same case-insensitive comparison reason as ddl_columns above.
  live_columns="$(run_query "DESCRIBE ${database}.${dataset}" \
    | awk '{print $1, $2}' | tr '[:upper:]' '[:lower:]')"
  declared_columns="$(ddl_columns "$sql_file")"

  missing=()
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    name="$(echo "$line" | awk '{print $1}')"
    if ! grep -q "^${name} " <<<"$live_columns"; then
      missing+=("$line")
    fi
  done <<<"$declared_columns"

  removed_or_retyped=()
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    name="$(echo "$line" | awk '{print $1}')"
    declared_line="$(grep "^${name} " <<<"$declared_columns" || true)"
    if [ -z "$declared_line" ] || [ "$declared_line" != "$line" ]; then
      removed_or_retyped+=("$line")
    fi
  done <<<"$live_columns"

  if [ ${#removed_or_retyped[@]} -gt 0 ]; then
    echo "  Refusing to alter ${database}.${dataset}: the live table has column(s) this" >&2
    echo "  script will not drop or retype: ${removed_or_retyped[*]}" >&2
    echo "  This requires 'generate migrate' (R4, not yet built). Alter the table by hand," >&2
    echo "  or revert the contract change, then re-run this script." >&2
    exit 1
  fi

  if [ ${#missing[@]} -gt 0 ]; then
    add_clause="$(printf '%s, ' "${missing[@]}")"
    add_clause="${add_clause%, }"
    echo "  Adding column(s) to ${database}.${dataset}: ${missing[*]}"
    run_query "ALTER TABLE ${database}.${dataset} ADD COLUMNS (${add_clause})" >/dev/null
  fi

  echo "  done."
done
