#!/usr/bin/env bash
# scripts/bootstrap_github.sh -- generated by pipeline-automator scaffold (project init)
#
# One-time (re-runnable) setup of everything deploy-dev.yml / deploy-prod.yml need that
# cannot be discovered from files in this repository: the develop branch, two
# GitHub Environments, three secrets, one variable, a prod reviewer rule, and prod's
# deployment-branch restriction. Run once via `engineering-automation scaffold
# bootstrap-github <project_dir>`, after `gh repo create` -- never from create-project,
# which runs before any GitHub repository exists.
#
# Non-interactive use: export AWS_DEPLOY_ROLE_ARN_DEV, AWS_DEPLOY_ROLE_ARN_PROD and
# AWS_PLAN_ROLE_ARN before running; any left unset are prompted for with `read -rs` so
# a secret value is never typed as a command-line argument or written to a file.
#
# Does NOT set branch protection on main. Which required checks belong
# there depends on which workflows you keep; that is the one manual step this script
# leaves for you.
set -euo pipefail

if ! command -v gh >/dev/null 2>&1; then
  echo "gh (GitHub CLI) is required." >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "Run 'gh auth login' first." >&2
  exit 1
fi

repo="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
echo "Bootstrapping ${repo} ..."

is_private="$(gh repo view --json isPrivate --jq .isPrivate)"
if [ "$is_private" = "true" ]; then
  echo "NOTE: ${repo} is private. Environment protection rules (required reviewers," >&2
  echo "deployment-branch restriction) require GitHub Pro/Team/Enterprise on a private" >&2
  echo "repo; on Free, the prod reviewer below will be accepted by the API but not" >&2
  echo "enforced." >&2
fi

# --- develop branch -------------------------------------------------
if ! git ls-remote --exit-code --heads origin "develop" >/dev/null 2>&1; then
  echo "Creating develop from main ..."
  git fetch origin "main"
  git branch "develop" "origin/main"
  git push origin "develop"
else
  echo "develop already exists on origin, skipping."
fi

# --- environments: gh has no environment subcommand, PUT is the only route,
# and PUT is create-or-update, so this whole script is safely re-runnable. ---
echo "Creating/updating 'dev' environment ..."
gh api --method PUT "repos/${repo}/environments/dev" >/dev/null

echo "Resolving prod reviewer ..."
read -rp "GitHub username of the prod deploy reviewer: " prod_reviewer_login
prod_reviewer_id="$(gh api "users/${prod_reviewer_login}" --jq .id)"

echo "Creating/updating 'prod' environment (reviewer + branch restriction) ..."
gh api --method PUT "repos/${repo}/environments/prod" \
  -F "deployment_branch_policy[protected_branches]=true" \
  -F "deployment_branch_policy[custom_branch_policies]=false" \
  -F "reviewers[][type]=User" \
  -F "reviewers[][id]=${prod_reviewer_id}" >/dev/null

# --- secrets: never via --body -- gh secret set encrypts locally and sends
# straight to the API, so nothing lands in a commit or needs gitignoring. The
# residual exposure is shell history and the process table, not a file. ---
set_secret() {
  local secret_name="$1" value="$2"
  shift 2
  if [ -z "$value" ]; then
    read -rsp "Value for ${secret_name}: " value
    echo
  fi
  printf '%s' "$value" | gh secret set "$secret_name" "$@"
}

echo "Setting AWS_DEPLOY_ROLE_ARN for dev ..."
set_secret AWS_DEPLOY_ROLE_ARN "${AWS_DEPLOY_ROLE_ARN_DEV:-}" --env dev

echo "Setting AWS_DEPLOY_ROLE_ARN for prod ..."
echo "NOTE: this must be a DIFFERENT role than dev's -- one role assumable from both" >&2
echo "environments makes the prod approval gate decorative. Each role's OIDC trust" >&2
echo "policy must name the repo AND environment, e.g." >&2
echo "  repo:${repo}:environment:prod" >&2
set_secret AWS_DEPLOY_ROLE_ARN "${AWS_DEPLOY_ROLE_ARN_PROD:-}" --env prod

echo "Setting AWS_PLAN_ROLE_ARN (repository-scoped, read-only) ..."
set_secret AWS_PLAN_ROLE_ARN "${AWS_PLAN_ROLE_ARN:-}" --repo "$repo"

# --- variables: plain text, printed in logs -- correct for a region, wrong for
# anything secret. ---
read -rp "AWS region (e.g. eu-west-1): " aws_region
gh variable set AWS_REGION --body "$aws_region"

echo
echo "Done. One manual step remains: set branch protection on main"
echo "(required status checks, etc.) -- this script deliberately does not do that for you."
