# test_prepare_payroll_register_schema.py -- generated by pipeline-automator generate (create-job)
# Asserts each transformation's runtime output schema against the resolver's prediction
# in prepare_payroll_register_schemas.yaml. Parametrised over that YAML, not over hardcoded
# transformation names, so adding a transformation changes the YAML, not this file.

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from payroll_pipeline.tests._schema_fixtures import (
    Case,
    assert_schema_matches,
    empty_frame_for,
    transformation_cases,
)

if TYPE_CHECKING:
    from pyspark.sql import SparkSession


@pytest.mark.unit
@pytest.mark.parametrize("case", transformation_cases("prepare_payroll_register"), ids=lambda c: c.name)
def test_transformation_output_schema_matches_prediction(spark: SparkSession, case: Case) -> None:
    """Isolate one transformation: build its inputs from the *predicted* upstream schema
    (never by calling the upstream transformation), so one bad function cannot cascade a
    failure downstream. The transformations module import is deferred here rather than at
    module level so collecting this file never requires pyspark -- by the time this body
    runs, the `spark` fixture has already skipped the test if pyspark is unavailable."""
    from payroll_pipeline.jobs.prepare_payroll_register import prepare_payroll_register_transformations as T

    inputs = [empty_frame_for(spark, case.input_schemas[name]) for name in case.inputs]
    result = getattr(T, case.name)(*inputs)
    assert_schema_matches(result.schema, case.expected)
