# validate.py -- generated by pipeline-automator scaffold (project init)
"""Declared-versus-observed validation of a job's final output, before it is written.

Scope is deliberately narrow: this module checks only what the sink contract
*declares* against what the DataFrame *observes*. It contains no business rules
and no job-specific logic, so it is scaffold-owned and shared by every job in
this package, exactly like `read()` and `write()`.

What this module does NOT check, and why:

* **Nulls in non-nullable columns.** Iceberg enforces required fields at write.
* **Coercing the frame to the declared types.** A `.cast()` pass before writing
  would absorb the friction of Spark's decimal promotion, but Spark's `cast` is
  silent and lossy: narrowing a decimal truncates, an overflowing integer cast
  yields null, and a non-numeric string cast yields null. Worse, casting *after*
  validating means the frame that was checked is not the frame that was written.
  A type that does not match its declaration is an authoring fault, and the fix
  belongs in the transformation where a reviewer can see it.
* **Join cardinality.** A wrong join type is a per-transformation property, and
  this function only ever sees the terminal output. Enforcing it here would mean
  materialising every intermediate frame and counting rows, which breaks Spark's
  lazy plan and costs a full scan per transformation. It belongs to the static
  AST check in the tool's `core/generator/validate.py` and to the `unit` test
  tier, where input row counts are controlled.

What it checks that Iceberg cannot:

* **Sink-table drift.** Iceberg validates the frame against *the table*. If the
  table was built from a contract that has since changed and `make catalog-apply`
  was never re-run, Iceberg faithfully enforces the stale schema and the write
  succeeds. `_check_sink_table_matches_contract` is the only thing that notices.
* **Grain uniqueness.** Iceberg has no primary-key or unique constraint.
* **Declared value constraints.** Iceberg has no CHECK constraint.

Every data check is folded into a single aggregation so the frame is scanned
once, not once per check. The caller is expected to have cached `df` before
calling -- this function performs one Spark action, and without a cache the whole
transformation DAG is recomputed for the subsequent write.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib import resources
from typing import Any, cast

import pyspark.sql.functions as F
import yaml
from pyspark.sql import DataFrame, SparkSession

_SKIPPED = "skipped"


@dataclass(frozen=True)
class CheckResult:
    """The outcome of a single declared-versus-observed check.

    Attributes:
        name: Stable identifier, e.g. `grain_unique` or `constraint_min:amount`.
            Stable across runs so a run record consumer can trend it.
        status: `"passed"`, `"failed"`, or `"skipped"`.
        detail: One human-readable sentence. Present even when passing, so a
            record reader never has to infer what was checked.
        observed: Structured numbers behind `detail` -- always JSON-serialisable,
            because this lands in the run record verbatim.
    """

    name: str
    status: str
    detail: str
    observed: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ValidationResult:
    """The full outcome of one `validate()` call.

    Deliberately not an exception. `run()` records this on the run record first
    and raises second, so a failed validation produces a structured record
    naming every check rather than a stack trace naming one.
    """

    checks: list[CheckResult]

    @property
    def ok(self) -> bool:
        """True when no check failed. A skipped check does not fail validation."""
        return not any(c.status == "failed" for c in self.checks)

    @property
    def failures(self) -> list[CheckResult]:
        """Only the failed checks, in declaration order."""
        return [c for c in self.checks if c.status == "failed"]

    def as_record(self) -> dict[str, Any]:
        """Render for the run record's `metrics` dict."""
        return {
            "ok": self.ok,
            "checks": [
                {"name": c.name, "status": c.status, "detail": c.detail, **c.observed}
                for c in self.checks
            ],
        }

    def summary(self) -> str:
        """One line naming every failure, for the exception message."""
        return "; ".join(f"{c.name}: {c.detail}" for c in self.failures)


class ValidationFailed(Exception):
    """Raised by `run()` -- never by `validate()` -- when a check failed.

    Carries the full result so a caller that catches it can still emit the
    structured record rather than only the message.
    """

    def __init__(self, result: ValidationResult) -> None:
        super().__init__(f"output validation failed: {result.summary()}")
        self.result = result


def load_sink_contract(package: str, contract_name: str) -> dict[str, Any]:
    """Read the generated sink contract out of the installed package.

    Read via `importlib.resources` rather than a filesystem path because under
    Glue this package is a wheel inside `--extra-py-files`, where no source tree
    exists. This is why the sink contract lives in `contracts/` and not in
    `jobs/<job>/`: the wheel build excludes `jobs/**/*.yaml`.

    The `{name}_data_contract.yaml` filename follows the same convention as a
    hand-written source contract, deliberately: a sink contract *is* a source
    contract for whatever job consumes this dataset next, so the two must be
    interchangeable in name, location and model.

    Args:
        package: The contracts subpackage, e.g. `customers.contracts`.
        contract_name: The contract's `name`, which equals the sink dataset,
            e.g. `clean_orders`.

    Returns:
        The parsed `contract:` mapping.

    Raises:
        FileNotFoundError: If the contract is absent from the installed package,
            which in practice means the wheel was built before `create-job` ran.
    """
    filename = f"{contract_name}_data_contract.yaml"
    resource = resources.files(package).joinpath(filename)
    if not resource.is_file():
        raise FileNotFoundError(
            f"sink contract '{filename}' not found in package '{package}'. "
            "Re-run `generate create-job` and rebuild the wheel."
        )
    document = yaml.safe_load(resource.read_text(encoding="utf-8"))
    return cast(dict[str, Any], document["contract"])


def _check_frame_matches_contract(df: DataFrame, contract: dict[str, Any]) -> CheckResult:
    """Compare the output frame's schema against the contract, before the write.

    Iceberg performs the equivalent check at write time and would reject the same
    frame, so this is not the safety net -- it is *phase attribution*. Without it,
    a transformation that drops a column fails inside `write()` with an Iceberg
    exception phrased in table terms, and the run record blames the write phase
    for a fault that belongs to transform. With it, the same fault surfaces here,
    in contract language, naming the column.

    Costs nothing: `df.schema` is resolved from the logical plan, so this adds no
    Spark action and no scan.

    Type comparison is exact -- `decimal(18,2)` and `decimal(38,18)` are different
    types. Comparing by Python class instead (`isinstance(actual, type(expected))`)
    would pass both, and would also pass `array<string>` against `array<int>` and
    any two `struct<>`s whatever their fields.
    """
    declared = {c["name"]: c["type"] for c in contract["schema"]}
    actual = {f.name: f.dataType.simpleString() for f in df.schema.fields}

    missing = sorted(set(declared) - set(actual))
    extra = sorted(set(actual) - set(declared))
    mismatched = sorted(
        f"{n}: declared={declared[n]} observed={actual[n]}"
        for n in set(declared) & set(actual)
        if declared[n] != actual[n]
    )

    if not (missing or extra or mismatched):
        return CheckResult(
            name="output_matches_contract",
            status="passed",
            detail=f"output frame matches the sink contract ({len(declared)} columns).",
        )
    return CheckResult(
        name="output_matches_contract",
        status="failed",
        detail=(
            f"output frame does not match the sink contract — missing {missing}, "
            f"unexpected {extra}, type mismatches {mismatched}."
        ),
        observed={"missing": missing, "extra": extra, "mismatched": mismatched},
    )


def _check_sink_table_matches_contract(
    spark: SparkSession, table: str, contract: dict[str, Any]
) -> CheckResult:
    """Compare the live sink table's schema against the contract that describes it.

    This is the drift check, and the only one here Iceberg cannot perform: Iceberg
    validates the incoming frame against the *table*, so a table built from a
    superseded contract is enforced faithfully and wrongly. Metadata only -- no
    scan, no action on the data.

    Nullability is excluded for the same reason it is excluded from R1.1's schema
    assertion: Spark widens it on almost every derived expression, so comparing it
    produces noise. Column order is excluded because Iceberg binds by name.

    The remedy named in a failing `detail` distinguishes what `make catalog-apply`
    can and cannot fix, matching `scripts/apply_catalog.sh`'s additive-only
    migration exactly: a column the contract declares but the table lacks is
    fixable by re-running `catalog-apply` (it runs `ALTER TABLE ... ADD COLUMNS`
    for exactly that case); a column the table has that the contract no longer
    declares, or a type change on a shared column, is not -- `catalog-apply`
    refuses to drop or retype a column, so naming it as the fix here would send
    the operator in a circle.
    """
    declared = {c["name"]: c["type"] for c in contract["schema"]}
    actual = {f.name: f.dataType.simpleString() for f in spark.table(table).schema.fields}

    missing = sorted(set(declared) - set(actual))
    extra = sorted(set(actual) - set(declared))
    mismatched = sorted(
        f"{n}: contract={declared[n]} table={actual[n]}"
        for n in set(declared) & set(actual)
        if declared[n] != actual[n]
    )

    if not (missing or extra or mismatched):
        return CheckResult(
            name="sink_table_matches_contract",
            status="passed",
            detail=f"{table} matches the sink contract ({len(declared)} columns).",
            observed={"column_count": len(declared)},
        )

    fixable_by_catalog_apply = bool(missing) and not (extra or mismatched)
    remedy = (
        "Run `make catalog-apply` to add the missing column(s)."
        if fixable_by_catalog_apply
        else "`make catalog-apply` only adds missing columns -- it will not drop or "
        "retype existing ones. Alter the table by hand, or wait for `generate "
        "migrate` (R4, not yet built)."
    )
    return CheckResult(
        name="sink_table_matches_contract",
        status="failed",
        detail=(
            f"{table} has drifted from the sink contract — "
            f"missing {missing}, unexpected {extra}, type mismatches {mismatched}. {remedy}"
        ),
        observed={"missing": missing, "extra": extra, "mismatched": mismatched},
    )


def validate(
    spark: SparkSession,
    df: DataFrame,
    *,
    table: str,
    contract_package: str,
    contract_name: str,
) -> ValidationResult:
    """Check the final output against its declared sink contract.

    Performs exactly one Spark action over `df`: every data check is folded into
    a single aggregation. Cache `df` before calling if the same frame is about to
    be written, or the transformation DAG is computed twice.

    Args:
        spark: Active SparkSession, used only for the table-metadata read.
        df: The final transformed output, before writing.
        table: Two-part `{database}.{dataset}` sink identity, composed by
            `JobContext.table_identity`.
        contract_package: Contracts subpackage, e.g. `customers.contracts`.
        contract_name: Sink contract name, which equals the sink dataset, e.g.
            `clean_orders`. Resolves to `{contract_name}_data_contract.yaml`.

    Returns:
        A `ValidationResult`. **Never raises on a failed check** -- the caller
        records the result, then raises `ValidationFailed`. A validation failure
        is data, not control flow.
    """
    contract = load_sink_contract(contract_package, contract_name)
    checks: list[CheckResult] = [
        _check_frame_matches_contract(df, contract),
        _check_sink_table_matches_contract(spark, table, contract),
    ]

    unique_key: list[str] = contract["grain"]["unique_key"]
    columns: list[dict[str, Any]] = contract["schema"]

    # --- one pass ----------------------------------------------------------
    aggs = [F.count(F.lit(1)).alias("row_count")]

    if unique_key:
        aggs.append(F.count_distinct(*[F.col(c) for c in unique_key]).alias("distinct_grain"))
        # count_distinct skips any row holding a null in any of its arguments, so a
        # null grain key would otherwise deflate the distinct count and the
        # uniqueness check would pass on a frame that has no usable key at all.
        aggs.append(
            F.sum(
                F.when(
                    F.greatest(*[F.col(c).isNull().cast("int") for c in unique_key]) == 1, 1
                ).otherwise(0)
            ).alias("null_grain_rows")
        )

    bounded: list[tuple[str, str, int]] = []
    for col in columns:
        constraints = col.get("constraints") or {}
        for bound in ("min", "max"):
            if constraints.get(bound) is not None:
                alias = f"violates_{bound}__{col['name']}"
                predicate = (
                    F.col(col["name"]) < constraints[bound]
                    if bound == "min"
                    else F.col(col["name"]) > constraints[bound]
                )
                aggs.append(F.sum(F.when(predicate, 1).otherwise(0)).alias(alias))
                bounded.append((col["name"], bound, constraints[bound]))

    observed = df.agg(*aggs).collect()[0].asDict()
    row_count = observed["row_count"]

    # --- interpret ---------------------------------------------------------
    checks.append(
        CheckResult(
            name="row_count",
            status="passed",
            detail=f"{row_count} rows written.",
            observed={"row_count": row_count},
        )
    )

    if unique_key:
        distinct = observed["distinct_grain"]
        null_rows = observed["null_grain_rows"]
        duplicates = row_count - null_rows - distinct
        key = ", ".join(unique_key)
        if duplicates == 0 and null_rows == 0:
            checks.append(
                CheckResult(
                    name="grain_unique",
                    status="passed",
                    detail=f"({key}) is unique across {row_count} rows.",
                    observed={"distinct_grain": distinct},
                )
            )
        else:
            checks.append(
                CheckResult(
                    name="grain_unique",
                    status="failed",
                    detail=(
                        f"grain ({key}) is not unique: {duplicates} duplicate rows, "
                        f"{null_rows} rows with a null key, over {row_count} rows."
                    ),
                    observed={
                        "duplicates": duplicates,
                        "null_grain_rows": null_rows,
                        "distinct_grain": distinct,
                    },
                )
            )

    for name, bound, limit in bounded:
        violations = observed[f"violates_{bound}__{name}"]
        checks.append(
            CheckResult(
                name=f"constraint_{bound}:{name}",
                status="passed" if violations == 0 else "failed",
                detail=(
                    f"{name} within declared {bound} {limit}."
                    if violations == 0
                    else f"{violations} rows violate {name} {bound} {limit}."
                ),
                observed={"violations": violations, bound: limit},
            )
        )

    # `constraints.enum_ref` has nothing to resolve against until `enums/<name>.yaml`
    # exists (R2.2). Recorded as skipped rather than silently dropped, so the run
    # record shows the check was declared and deliberately not run.
    for col in columns:
        if (col.get("constraints") or {}).get("enum_ref"):
            checks.append(
                CheckResult(
                    name=f"constraint_enum:{col['name']}",
                    status=_SKIPPED,
                    detail=(
                        f"enum_ref '{col['constraints']['enum_ref']}' declared but enum "
                        "resolution is not implemented (R2.2)."
                    ),
                )
            )

    return ValidationResult(checks=checks)
