# modules/catalog/main.tf -- generated by pipeline-automator scaffold (project init)
# Glue Catalog databases for this data product's Iceberg sinks.
# One database per medallion layer, created once at project init -- not per job, and
# not spliced through an AMEND marker, since the layer set is already project-wide.
# The table itself is generated DDL (see infra/catalog/), never Terraform-managed:
# Iceberg rewrites metadata_location on every commit, which Terraform state cannot
# tolerate without permanent drift. This module never grants glue:CreateTable --
# the job never creates a table, only `make catalog-apply` does, under a separate
# deployer identity.

locals {
  common_tags = merge(var.tags, {
    Environment = var.environment
    ManagedBy   = "terraform"
    Module      = "catalog"
  })
}

resource "aws_glue_catalog_database" "this" {
  for_each = toset(["raw", "preprocessed", "processed"])

  name        = "${replace(var.name_prefix, "-", "_")}_${each.key}"
  description = "Iceberg catalog database for the ${each.key} layer of ${var.data_product}."

  tags = local.common_tags
}

# make catalog-apply's Athena workgroup, named to match scripts/apply_catalog.sh's own
# "${DATA_PRODUCT}-${ENVIRONMENT}-catalog" computation exactly.
resource "aws_athena_workgroup" "catalog" {
  name = "${var.name_prefix}-catalog"

  configuration {
    enforce_workgroup_configuration    = true
    publish_cloudwatch_metrics_enabled = true

    result_configuration {
      output_location = "s3://${var.results_bucket_name}/athena-results/${var.name_prefix}-catalog/"
    }
  }

  tags = local.common_tags
}
