# modules/catalog/outputs.tf -- generated by pipeline-automator scaffold (project init)

output "catalog_database_names" {
  description = "Map of medallion layer to its Glue Catalog database name."
  value       = { for k, v in aws_glue_catalog_database.this : k => v.name }
}

output "catalog_database_arns" {
  description = "Map of medallion layer to its Glue Catalog database ARN."
  value       = { for k, v in aws_glue_catalog_database.this : k => v.arn }
}
