# modules/catalog/variables.tf -- generated by pipeline-automator scaffold (project init)

variable "name_prefix" {
  description = "Prefix applied to catalog database names (typically '<data_product>-<environment>')."
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "data_product" {
  description = "Name of the data product these catalog databases belong to."
  type        = string
}

variable "results_bucket_name" {
  description = "S3 bucket the Athena workgroup writes query results to (the scripts bucket)."
  type        = string
}

variable "tags" {
  description = "Tags applied to all resources in this module."
  type        = map(string)
  default     = {}
}
